### ISSUE TITLE
page d'accueil : retirer le bloc 1600 déclarations / 3 instructrices / 50 p cent de produits circulants non déclarés

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#1023]
Demande last minute du BEPIAS.

- car il faut éviter le terme d’instructrice comme cela a été rappelé hier par Perrine (que je remercie d’avoir devancé ma remarque) 
- et il n’est pas validé par la DGAl d’afficher les ressources ;
- la sous-déclaration est une estimation qui n’a pas fait l’objet d’une étude robuste et nous ne pouvons la justifier en cas de demande presse (gros suivi sur ce sujet)

**Comment by pletelli** [comment]
J'ai créé https://github.com/betagouv/complements-alimentaires/issues/1022
