### ISSUE TITLE
En tant que pro, je peux renseigner la qtté pour les substances non obligatoires

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#1089]
L'étiquetage doit être le reflet exact de ce qu’ils déclarent sur Compl’Alim or pour pouvoir mettre en avant certains effets du CA ils ont besoin de préciser que leur produit en contient X dose - enjeu commercial.

**Comment by alemangui** [comment]
@HeleneDubourdieu PI cet issue fait réf à ton retour https://www.notion.so/betagouv-dinum/Quickwin-Ajouter-quantit-substance-si-quantit-non-obligatoire-42880ef358df4e0eb1db9e63d6fddd06
