### ISSUE TITLE
Identifier les déclarations article 15 nécessitant une instruction obligatoire

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#1097]
**Si le CA contient dans sa compo:** 

- Plantes dont le champ name se trouve dans
  - 'Cannabis sativa L.', -> certaines parties pas ok ?
  - 'Griffonia simplicifolia (DC.) Baill.' -> seules les graines sont ok ?
  - 'Curcuma longa L.' -> concentration en camphre à surveiller
  - Aloe*, Rhamnus alpina L., Rhamnus cathartica L., Frangula purshiana Cooper, Cassia fistula L. (ajouter le synonyme Cassia Senna ?), Rheum palmatum L., Rheum officinale Baill., Frangula dodonei Ard. (ajouter le synonyme Ramnus frangula) -> subst "dérivés hydroxyanthracéniques"
  - Camellia sinensis (L.) Kuntze -> subst "épigallocatéchine-gallate (EGCG)" ?
- Substances dont le champ name se trouve dans [Melatonine, Glucosamine, Chondroïtine, chlorydrate de berberine]
- Micro-organisme dont le champ name dans [ Monascus purpureus]
- Ingrédients contentant de l'alcool : [Alcool, Alcool éthylique, Alcoolat de membranes cellulaires, Cognac,  Vinaigre, Vin, Vin rouge, Vin de pomme] 

**Si le type de préparation est :**
    - Elixir [CE CHOIX N'EXISTE PAS, SERAIT-CE POSSIBLE DE LE CREER ? #1098] 
    - Alcoolat
    - Alcoolature
    - Macérât alcoolique
    - Macérât hydroalcoolique
    - Teinture

**Si la pop. cible du CA est :**
    - Femmes allaitantes 
    - Femmes enceintes
    - Nourrissons de 0 à 5 mois
    - Nourrissons de 6 à 11 mois
    - Enfants en bas âge de 1 à 3 ans 
    - Enfants de 4 à 10 ans
    - Adolescents de 11 à 17 ans

**Si la forme galénique du CA est :**
    - Jus 
    - Autre 
    
L'atelier avec le BEPIAS pour comprendre [ici](https://www.notion.so/betagouv-dinum/Distinction-articles-15-16-17-et-18-b5e365e834bf4197945ccb6b4d12bd4a?d=13da83028c8b4adea485939f98cda71e#bfd2fa594c6f409f9c0ccffd53fa26f5)

**Comment by Fantine-py** [comment]
Le BEPIAS ne nous a pas transmis la liste des plantes/substances encadrées par le RCE1925/2006

**Comment by pletelli** [comment]
La forme galénique "Jus" n'existe pas.

Est-ce que Elixir devrait être une forme galénique plutôt qu'une préparation ?
