### ISSUE TITLE
Ajouter l'option "Elixir" dans la liste des types de préparation

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#1098]

**Comment by pletelli** [comment]
@HeleneDubourdieu 
J'ai cru comprendre que vous aviez prévu une newsletter.
Je me demande si vous voulez informez les déclarants de la possibilité de choisir Elixir dans la NL (c'est un peu insignifiant, mais de ce que Emmanuelle racontait c'est très demandé)

**Comment by HeleneDubourdieu** [comment]
@pletelli hello, je vais le rajouter en effet dans la prochaine NL :)
