### ISSUE TITLE
Bug : en tant qu'utilisateur, lorsqu'une entreprise m'ajoute comme déclarant, je reçois un mail m'invitant à "créer mon compte" alors que j'ai déjà un compte sur Compl'Alim.

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#1120]
Par exemple ce Monsieur a déjà un compte. 

C'est un problème de formulation du bouton car s'il clique dessus, il n'a pas besoin de se créer un nouveau compte, Compl'Alim reconnait son adresse mail. 

Donc il faudrait changer la formulation du bouton par "Accepter l'invitation" par exemple ou "Valider" ?

![Image](https://github.com/user-attachments/assets/8f4a772c-cbcb-4f91-ab9b-270cfe3d6615)

**Comment by alemangui** [comment]
@Fantine-py je viens de modifier le bouton à "Valider" sur Brevo. En cas de besoin, le lien pour le template est : https://my.brevo.com/camp/template/16/message-setup?editor=v6
