### ISSUE TITLE
Recopier la dose de substances contenues dans la composition 

### ISSUE THREAD

**Issue by HeleneDubourdieu** [betagouv/complements-alimentaires#1168]
Pour les substances, recopier la dose de substance si la recherche de dépassement de dose ne se fait qu'au niveau de l'onglet "substances contenues dans la compo"
<img width="542" alt="Capture d’écran 2024-10-22 à 06 26 35" src="https://github.com/user-attachments/assets/bb70c5da-ee5a-42cb-95db-fd12448df2d1">

**Comment by alemangui** [comment]
Côté UI je ne suis pas sur car la même substance peut être contenue dans des ingrédients différents et idéalement ce champ ne changerait pas en dépendant de la compo, mais p-e je suis en train de mal comprendre.

**Comment by alemangui** [comment]
Pareil pas sur de la prio MVP?

**Comment by HeleneDubourdieu** [comment]
En effet je le mets en KO une même substance peut être contenue dans des ingrédients différents
