### ISSUE TITLE
Ajouter pays dans la liste des pays pouvant déclarer un CA

### ISSUE THREAD

**Issue by HeleneDubourdieu** [betagouv/complements-alimentaires#1180]
Le pays Suisse et le Royaume Uni ne sont pas proposés au moment du choix du pays à l'inscription sur la plateforme.

Pouvez-vous les ajouter ?

Merci

**Comment by alemangui** [comment]
Il semblerait que la télédéclaration soit seulement disponible pour les pays membres de l'EEE, et donc ceux qu'on a déjà dans la liste (sans la Suisse ni le Royaume-Uni).

Dans la [FAQ de Téléicare](https://teleassistance.dgccrf.finances.gouv.fr/FAQ/Faq/?app=TELEICARE) :

> ### Qui peut adhérer à la téléprocédure ?
> Toute entreprise localisée en France, dans l’Union européenne ou dans un État partie à l’accord sur l'EEE (Norvège, Lichtenstein, Islande) souhaitant déclarer des compléments alimentaires pour le compte de sa société ou pour un mandant.

J'ai également cherché dans le code source de Téléicare et on n'a pas la possibilité de sélectionner ni la Suisse ni le Royaume-Uni.
