### ISSUE TITLE
BUG : Téléchargement attestation n°715

### ISSUE THREAD

**Issue by HeleneDubourdieu** [betagouv/complements-alimentaires#1268]
https://github.com/user-attachments/assets/75181d64-b28a-466c-b0b7-851ea7d39733

Testé avec cet utilisateur : https://compl-alim.beta.gouv.fr/admin/data/user/529/change/

Il semble que ce soit un bug isolé

**Comment by alemangui** [comment]
L'article de la déclaration en question est "saisine ANSES", et on n'a donc pas de template. L'erreur Sentry est ici : https://sentry.incubateur.net/organizations/betagouv/issues/131276/?project=146&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=1

Pour ce cas particulier on peut changer l'article sur l'admin s'il s'agit d'un 15 ou 16.

Plus généralement, est-ce qu'on veut permettre la validation d'une déclaration ayant un article "saisine ANSES" ?

**Comment by HeleneDubourdieu** [comment]
On en a parlé sur Tchap mais je le rajoute ici.
Pas de possibilité de valider une saisine anses.
La déclaration doit-être automatiquement re qualifiée

**Comment by HeleneDubourdieu** [comment]
https://github.com/betagouv/complements-alimentaires/issues/1277
