### ISSUE TITLE
Recherche ingrédient depuis la page d'un ingrédient

### ISSUE THREAD

**Issue by HeleneDubourdieu** [betagouv/complements-alimentaires#1274]
https://github.com/user-attachments/assets/d8b4a3da-9b3d-47d8-abc0-89de48c571d5

Alex,

Est-ce que c'est un souhait que depuis la page d'un ingrédient on ne puisse pas rechercher un nouvel ingrédient ?

Merci beaucoup pour ton aide

Note Hélène : (remonté par user/1459)

**Comment by alemangui** [comment]
Hello @HeleneDubourdieu, on peut déjà chercher, il suffit de clicker "Entrer". Ce qui ne s'affiche pas c'est l'autocomplete. On peut le mettre aussi en place si besoin.

**Comment by HeleneDubourdieu** [comment]
Yep mais c'est pas du tt urgent

**Comment by HeleneDubourdieu** [comment]
ok testé merci
