### ISSUE TITLE
En tant qu'instructrice / viseur, je souhaite être bloquée si je valide une déclaration saisine anses

### ISSUE THREAD

**Issue by HeleneDubourdieu** [betagouv/complements-alimentaires#1277]
Les déclas saisine anses ne doivent pas être "validables".
L'instructrice doit obligatoirement modifier le numéro de l'article.

Comportement actuel : 
- L'instructrice a la possibilité de valider une déclaration dite saisine anses
- Le pro reçoit un mail pour télécharger son attestation
- Celle-ci est en erreur 500 car le numéro de l'article est saisine anses

Comportement souhaité : 
- Si l'instructrice autorise une déclaration avoir une pop up qui apparait ou autre : "merci de changer le numéro de l'article de la déclaration"

**Comment by HeleneDubourdieu** [comment]
![Image](https://github.com/user-attachments/assets/4e5facec-0757-45fb-96da-8135d374517e)
possible d'afficher cette info dans la partie signature / visa ?

**Comment by alemangui** [comment]
Lié à #1387
