### ISSUE TITLE
Double Snapshot 

### ISSUE THREAD

**Issue by HeleneDubourdieu** [betagouv/complements-alimentaires#1395]
**Contexte :** 
Un Snapshot est envoyé dès que le user change le statut de la déclaration de DRAFT  →  AWAITING_INSTRUCTION.

**Problème :** 
Si on repasse la déclaration en DRAFT pour que le pro puisse modifier quelque chose, puis que celui-ci l'envoi en AWAITING_INSTRUCTION : un second Snapshot est créé. Ce qui bloque la validation automatique de la déclaration.

Pour les 3 déclarations ci-dessous je suis intervenue pour modifier le statut des déclarations : 
<img width="902" alt="Capture d’écran 2024-12-19 à 11 07 53" src="https://github.com/user-attachments/assets/19e7d91d-2db4-4037-b9be-9de9b54b2a8c" />

**Comment by alemangui** [comment]
Pas sur que ça soit un bug... en remettant la déclaration en draft l'algo a raison a dire qu'au moins un aller-retour entre l'admin et le pro a eu lieu.

Si on veut modifier le comportement (çad exclure les cas où manuellement on remet en draft une déclaration) on peut en créer une feature.

Est-ce que ce cas arrive souvent ? Car la manip manuelle depuis l'admin pour modifier une déclaration pourrait avoir d'autres effets secondaires :thinking:

**Comment by HeleneDubourdieu** [comment]
Merci pour les infos.
Effectivement il pourrait y avoir des conséquences.

Je vais valider manuellement les 3 déclarations et laisser ce ticket en piste pour 2025.
