### ISSUE TITLE
Nouveau modèle de données

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/complements-alimentaires#17]
```[tasklist]
### Tasks
- [x] dessiner l'ancien modèle de donner
```

**Comment by JenniferStephan** [comment]
@alemangui ok pour toi de mettre ici les infos collectées suite à ton échange avec le pole SQL (sic) de la DGCCRF ?

**Comment by alemangui** [comment]
Je me permet de fermer cet issue suite à l'import des données
