### ISSUE TITLE
Obtention de l'historique de déclaration auprès de la SICCRF

### ISSUE THREAD

**Issue by pletelli** [betagouv/complements-alimentaires#172]
- [x] Obtention du schéma modèle de données -> extract as pdf
- [x] Obtention du code source
- [x] Rencontre avec la SICCRF le 26 janvier ? avec DD de 200gb

- [ ] Dump régulier -> selon le guide utilisateur le dump quotidien fait seulement 4Go

**Comment by Fantine-py** [comment]
Hello @pletelli je ferme ce ticket car il me semble qu'on est il est redondant avec #717 ?

**Comment by pletelli** [comment]
Oui parfait !
