### ISSUE TITLE
Modélisation User / Entreprise (validation du concept et personas)

### ISSUE THREAD

**Issue by alemangui** [betagouv/complements-alimentaires#181]
### Idées suites au brainstroming sur les users
*idées initiales, à ajuster en fonction de nos découvertes au fil du développement*

- Besoin d'avoir des objets en plus de `User` pour ajouter des rôles, pour une meilleure gestion des données
- Avoir des champs désactivables sur les rôles (`is_active`) afin de permettre une désactivation temporaire de 1 ou plusieurs rôles. (il y a sûrement d'autres méthodes pour gérer ça)
- 1 utilisateur pourrait avoir de 0 rôle à N rôles :
	- A priori, pas d'intérêt à forcer un utilisateur à avoir au moins 1 rôle
	- L'utilisateur superadmin est un bon exemple d'utilisateur ou un rôle supplémentaire n'est pas nécessaire
	- La possibilité d'avoir aucun rôle permet de créer l'utilisateur plus rapidement et donc rendre l'expérience utilisateur meilleure
- Si on ouvre l'admin à des utilisateurs (déconseillé, mais gain de temps indéniable...), il faut faire très attention à la data consistency => penser à overrider les méthodes `clean()` ou  `save()` pour empêcher un modèle d'être dans un état non désiré (par exemple 2 champs à `True` alors qu'ils ne sont pas censés pouvoir l'être)

- [à vérifier] la raison de ne pas mettre des `is_profile_1` et `is_profile2` c'est parce que :
	- on créé de la redondance de donnée qui peut mener à une inconsistence
		- Ex : `is_profile_1 == True` alors que `user.is_profile_1 is None` 
	- on peut retrover l'info nous-même avec l'introspection Django sur les related fields

- Permissions → à priori non pour le moment. Sert à gérer une granularité fine avec un fort besoin dynamique. Mais l'option reste possible, et mutualisable avec les profils.

**Besoins**
- Se focaliser sur 2 rôles seulement au début
	- Faire des tests avec des users ayant 0 rôle, 1 rôle, et 2 rôles pour avoir tous les cas de figure.
- Jointures à penser (optimiser avec des `select/prefetch_related`)
- Avoir du sucre syntaxique (ex : managers, override de `get_queryset` pour garder un code le plus simple possible malgré une architecture distribuée)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/complements-alimentaires/issues/276
```

**Comment by ddahan** [comment]
@alemangui tu voulais que je prenne ce sujet n'est-ce pas ? :)
