### ISSUE TITLE
Remplacer dotenv par django-environ

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#195]
Le package dotenv utilisé est assez basique et ne fait que charger le .env dans l'environnement. Du coup ça force à parser manuellement le contenu des variables, et c'est assez error-prone les booléens en string comme : 

```
SECURE_SSL_REDIRECT = os.getenv("FORCE_HTTPS") == "True"
```

Avec le package django-environ il y a une surcouche intégrée pour gérer ce parsing (bool, int, liste, etc.). Ca donnerait en équivalent :

```
SECURE_SSL_REDIRECT = env("FORCE_HTTPS", cast=bool)
```

**Comment by ddahan** [comment]
Autre exemple pertinent :

```python
ALLOWED_HOSTS = [x.strip() for x in os.getenv("ALLOWED_HOSTS").split(",")]
```

**Comment by ddahan** [comment]
Un fonctionnement à noter c'est que par défaut django-environ râle s'il ne trouve pas la variable dans le .env, ce qui permet de ne rien oublier. Du coup pour les variables AWS dans les settings, je voulais faire un truc du genre :

`# Media and file storage
DEFAULT_FILE_STORAGE = env("DEFAULT_FILE_STORAGE")

```python
if DEFAULT_FILE_STORAGE == "storages.backends.s3.S3Storage":
    AWS_ACCESS_KEY_ID = env("CELLAR_KEY")
    AWS_SECRET_ACCESS_KEY = env("CELLAR_SECRET")
    AWS_S3_ENDPOINT_URL = env("CELLAR_HOST")
    AWS_STORAGE_BUCKET_NAME = env("CELLAR_BUCKET_NAME")
    AWS_LOCATION = "media"
    AWS_QUERYSTRING_AUTH = False
```

N'ayant pas encore accès aux var d'env sur clevercloud, est-ce que quelqu'un peut me confirmer que la valeur de DEFAULT_FILE_STORAGE quand on utilise AWS est bien `storages.backends.s3.S3Storage` ?

**Comment by alemangui** [comment]
C'est bien `storages.backends.s3.S3Storage` coté CC, et la solution de l'if me semble reaisonable pour ce cas (car les var `AWS_...` sont utilisées seulement par le storage S3). 

Par contre, pour d'autres cas, sauf erreur de ma part django-environ a bien une feature `default=` non ? Par ex, si jamais on décide volontairement d'omettre une env var optionnelle on peut ajouter un `default=None` aux settings ?

**Comment by ddahan** [comment]
Oui j'utilise bien le feature `default=` par exemple ici :

 ```
 MEDIA_ROOT = env("MEDIA_ROOT", default=os.path.join(BASE_DIR, "media"))
 ```
 
 Mais en effet dans ce cas précis, ça me semble plus clair et explicite de dire que les variables AWS doivent exister uniquement dans le cas d'un storage type s3, plutôt que ce genre de code :
 
 ```
AWS_ACCESS_KEY_ID = env("CELLAR_KEY", default=None)
AWS_SECRET_ACCESS_KEY = env("CELLAR_SECRET", default=None)
AWS_S3_ENDPOINT_URL = env("CELLAR_HOST", default=None)
AWS_STORAGE_BUCKET_NAME = env("CELLAR_BUCKET_NAME", default=None)
 ```
