### ISSUE TITLE
Afficher les messages d'erreur provenant du back-end

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#213]
Pour le moment, lorsqu'une erreur a lieu côté back-end, par exemple lorsqu'un formulaire est envoyé, nous affichons un message générique comme `"Une erreur est survenue, veuillez réessayer plus tard."`

Il est nécessaire d'avoir un mécanisme générique permettant d'inclure les messages de retour de l'API, pour permettre à l'utilisateur de connaitre les causes de l'erreur. Ainsi, nous devrons gérer dans Vuelidate à la fois les erreurs front et les erreurs back.

**Exemple**
Lors de l'inscription à l'info-lettre, nous devrions avoir ces messages d'erreur possible sur le champ e-mail :
- Erreur front : `Ce champ doit contenir un email valide`
- Erreur back : `Cet email existe déjà, vous êtes déjà inscrit`
```[tasklist]
### Tasks
- [ ] Une tâché liée est d'arrêter de faire un try/except global sur un endpoint pour catcher une erreur inconnue.
- [ ] [BUG] corriger les erreurs 500 sur `/resultats/?q=Eu&page=1` avec une erreur propre qui vient du back
```

**Comment by ddahan** [comment]
- Ce système de gestion d'erreur doit inclure la méthode `verifyResponse` actuellement retirée (temporairement) pour simplifier la migration.
- Une piste à explorer pour la gestion est : https://vueuse.org/core/useFetch/#creating-a-custom-instance

**Comment by ddahan** [comment]
Je pense que cette issue devient indispensable à traiter, parce qu'une simple feature comme le login ou le signup (qui doit retourner une ou des erreur(s) du back) n'est pas réalisable en entier. Par exemple, afficher "une erreur est survenue" si on entre le mauvais mot de passe n'est pas acceptable je pense.
De plus, plus on attend, plus il faudra potentiellement mettre à jour de features pour être compatibles avec le mécanisme.

Qu'en pensez-vous @alemangui @pletelli ?

**Comment by alemangui** [comment]
@ddahan Oui, ça dépend du temps/effort pour le mettre en œuvre mais en générale je suis pour commencer à regarder cette fonctionnalité.

L'alternative c'est de gérer les différents codes erreur HTTP. Les erreurs _400 bad request_ peuvent contenir un message d'erreur custom qu'on peut afficher au lieu de "une erreur est survenu". D'ailleurs ces codes HTTP devront être utilisés correctement même si on prend la décision de mettre en place toute la feature (e.g., 400 pour une requête incorrecte, 403 pour un souci des droits, etc etc).
