### ISSUE TITLE
Remplacer `fetch` classique par `useFetch`

### ISSUE THREAD

**Issue by alemangui** [betagouv/complements-alimentaires#234]

**Comment by ddahan** [comment]
@alemangui Comme je disais dans la PR, il reste juste ces endroits-là où je te laisse faire la modif par toi-même :


![Image](https://github.com/betagouv/complements-alimentaires/assets/1933516/09e4e799-3528-4c55-a466-e072966c5979)

Je ferme quand même l'issue en partant du principe que ça sera une tâche à part.
