### ISSUE TITLE
Utiliser des slugs plutôt que des noms dans les urls

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#255]
Actuellement, un élément est affiché comme ceci en url : `94--plante--Daucus%20carota%20L.`

On peut utiliser [cet outil Django ](https://docs.djangoproject.com/en/5.0/ref/utils/#django.utils.text.slugify) pour régler le soucis, en l'intégrant directement dans une mixin.

**Comment by alemangui** [comment]
Pour être sur d'avoir bien compris, la suggestion est d'avoir dans l'URL `94--plante--Daucus-carota-L.`? (donc `-` au lieu d'espaces non?)

Ce slug est créé côté frontend un peu éparpillé. L'idée étant d'avoir les infos nécessaires pour fetcher les infos de l'élément (_id_ et _type_) ainsi que le nom pour des raisons de SEO. L'ID et le type sont au début dans le cas rare où le séparateur soit aussi présent dans le nom.

C'est pourquoi des fois on voit dans le code :

```javascript
`${element.id}--element--${element.name}`
```
Une alternative serait d'avoir deux fonctions globales (p-e dans `utils`) : une pour générer ce slug et une autre pour extraire les sections (id, type, name) à partir d'un slug. Dans la première on pourrait faire un `replace(" ", "-")` ou autre traitement qu'on juge nécessaire.
