### ISSUE TITLE
Séparation des apps Django

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#273]
Actuellement, il n'existe qu'une seule app Django : `data` qui contient tous les models. Cela posera sûrement des soucis à la longue, notamment à cause des conflits sur les migrations (qui peuvent cela-dit être réglés avec un merge).

#### Exemple de problème rencontré 
Django n'est pas capable de voir automatiquement que quand je déplace le model User de app1 à app2, il s'agit du même modèle. Donc dans sa migration il delete User, et le recréé, sur ce qui au passage efface les données :slightly_smiling_face:

#### Pistes à explorer
- Modifications manuelles des migrations pour gérer ce cas
- Cas extrême : rebuild de la base et reset des migrations

**Comment by ddahan** [comment]
Lié : https://github.com/django/django/pull/16585

**Comment by alemangui** [comment]
My two cents : Cette séparation est souhaitée et bienvenue mais pas complètement indispensable. 

Les conflits qui ne concernent pas la même table peuvent se régler facilement et ceux qui concernent la même table seront toujours un problème après le split.

Aujourd'hui, Django n'arrive en effet pas à détecter un changement d'app. Cette [feature request est ouverte](https://code.djangoproject.com/ticket/24686) depuis pas mal d'années mais récemment il y a eu un push plus grand pour la mettre en oeuvre (avec par exemple des débuts de PRs d'une éventuelle opération `MoveModel` : [PR 1](https://github.com/django/django/pull/16585), [PR 2](https://github.com/django/django/pull/11920)...).

Sans cette feature c'est très galère de faire le changement, car il faut passer par une opération `SeparateDatabaseAndState` intermédiaire qui est risquée.

Afin de ne pas passer trop de temps dessus on pourrait décider de s'y pencher lors que la feature côté Django sera en place, ou bien si on trouve un moyen pas trop chronophage de le mettre en place.

**Comment by ddahan** [comment]
Je suis d'accord. J'en profite pour ajouter des extraits du livre des bonnes pratiques + chatGPT pour étayer le "souhaitée et bienvenue mais pas complètement indispensable" :

<img width="606" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/cea20ee8-a8c4-4676-a862-fd5e03c331f3">

<img width="585" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/6b713397-dba1-4da4-ab9b-c9afb36ef672">

<img width="612" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/3e2d21b5-88ea-4e50-bf6f-5cc582d2bdb6">
