### ISSUE TITLE
Rationnalisation FR vs ENG dans le code

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#335]
Le projet contient un mélange de commentaires en anglais et en français.
Il faudrait : 
- écrire une convention sur les langues à utiliser dans chaque cas (commentaires et autres) (sachant que ça a du être fait entre nous oralement)
- mettre à jour tous les endroits du code nécessaires (potentiellement beaucoup de fichiers)

**Comment by ddahan** [comment]
@alemangui @pletelli OK pour que je prenne tous les fichiers et que je mette tous les commentaires en français un de ces 4 où j'ai envie de travailler sans trop réfléchir ?

**Comment by pletelli** [comment]
Ok pour moi !
J'étais sûre qu'on devait tout franciser après l'avoir lu dans le guide de la communauté beta.gouv
![image](https://github.com/betagouv/complements-alimentaires/assets/1618987/6b5ec8f8-61ec-49f8-89a8-83aedb1ebaa0)

https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-fais-des-choix-technologique/standards-de-qualite-beta.gouv.fr

Mai sj'ai eu du mal à retrouver ce passage et je suis aussi tombée sur https://sillon.incubateur.net/docs/community-and-open-source/english-or-french/ qui va un peu à l'inverse.

**Comment by ddahan** [comment]
Ah merci pour les liens @pletelli !
<img width="750" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/56896ac1-b588-4ac2-9976-2e126d62436d">
En lisant ça cela dit, je sais toujours pas en quelle langue écrire les commentaires, parce que ça peut être soit du métier, soit du pure tech, et souvent un mix des deux.

Ce qui me rassure c'est que pour les readme, PR, et docs, on est bien en français, donc pas si mals au final j'ai l'impression

**Comment by alemangui** [comment]
Je me pemets de fermer celui-ci suite au std mis en place depuis notre discussion
