### ISSUE TITLE
Nettoyer l'appel aux services externes selon l'environnement

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#349]
Par exemple, côté dév, on n'a pas besoin d'avoir les stats. Cela évitera :
- de polluer la console avec des "fausses" erreurs pendant le dév :
- des appels à un service qui ne devraient pas avoir lieu
<img width="808" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/2eb2179d-76a5-4da8-96be-8cc9bf37c856">

**Comment by alemangui** [comment]
Je dirais plutôt en fonction de la variable d'environnement et non pas de l'environnement (ex si on n'a pas l'env var matomo, ne pas faire les calls)

**Comment by ddahan** [comment]
Oui bien sûr !
Les `if env == "DEV" ... else ...` c'est pas 12-factor compliant !
