### ISSUE TITLE
Utiliser les nom des routes plutôt que les urls

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#350]
Doit-on ajouter une convention sur le fait de privilégier le nom des routes plutôt que les urls dans le routeur ?
(jusqu'ici il semble qu'on utilise l'un ou l'autre sans raison apparente).

Avis chatGPT

> In Vue 3 with Vue Router, it's generally recommended to push routes using names rather than URLs for a few reasons:

> Readability: Named routes make your code more readable and easier to understand. When you use names, it's clear which route you're navigating to without having to decipher the path structure.

> Maintainability: If you need to change the URL of a route, you can do so in one place (the router configuration) without having to update all references throughout your app. This is not the case if you use URLs directly.

> Parameters and Query Handling: Named routes make it easier to work with dynamic route parameters and query strings. The syntax for passing parameters and queries is more intuitive when using route names.

**Comment by alemangui** [comment]
C'est un peu ce qu'on fait non ? De ce que je vois dans le code `router.push({ name: "ElementSearchResultsPage", query: { q: searchTerm.value } })`, `router.push({ name: "ElementSearchResultsPage", query: { q: term } })`... as tu trouvé des endroits où l'on utilise le vue router avec l'URL cru ?

**Comment by ddahan** [comment]
Ah my bad, les endroits où j'ai vu des urls en dur sont les `to`, par exemple ici : 

```js
const navItems = [
  {
    to: "/accueil",
    text: "Accueil",
  },
  {
    to: "/entreprises",
    text: "Entreprises",
  },
  {
    to: "/blog",
    text: "Blog",
  },
]
```

Du coup je vois pas de moyen simple de changer ça.
Je close l'issue mais si vous avez une idée, n'hésitez pas.
