### ISSUE TITLE
Exploration du renvoi de données/messages de DRF en cas de succès

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#351]
_Cette issue fait suite au mécanisme de gestion d'erreurs côté back._

Vu que c'est le back qui renvoie les messages d'erreurs, veut-on faire le symétrique pour les messages sans erreur par cohérence, ou laisser comme tel (`if (response.value.ok) {addSuccessMessage("foo")}`) (évaluer avantages/inconvénients).

**Comment by ddahan** [comment]
Si on change :

**Avantages**
- Code plus simple côté front, l'affichage des messages est automatique (équivalent `handleError`)
- Gain en cohérence d'avoir le même fonctionnement, peu importe le type de message (succès ou erreur)

**Inconvénients**
- Couplage front/back plus fort
- Workflow moins visible juste en lisant le code front (si on sait pas que le back renvoie un message d'erreur, on peut pas savoir qu'il s'affiche)

**Comment by alemangui** [comment]
Je ne sais pas si le jeu en vaut la chandelle. La plupart des calls n'ont pas besoin d'un affichage en cas de succès, et d'autres nécessitent des actions particulières (changer une page, modifier un modèle, etc), du coup je préfère la souplesse de laisser à chaque composant de gérer son cas de succès individuellement.

**Comment by ddahan** [comment]
Je pense un peu comme toi. Je propose de laisser cette issue ouverte "pour info", et la ressortir que si le besoin se fait vraiment sentir plus tard.
