### ISSUE TITLE
Ajout de la GH Action Django Migration Checker

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#353]
https://github.com/marketplace/actions/django-migration-checker

(encore plus utile tant qu'on a qu'une seule grosse app)

**Comment by alemangui** [comment]
Le package utilisé derrière django-migration-checker n'a pas été modifié depuis plus de deux ans et n'est pas super bien vendu par leurs auteurs.

![image](https://github.com/user-attachments/assets/96b4fb5c-2abe-444f-ab53-80c166247029)
