### ISSUE TITLE
Environnement de staging VS démo

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#354]
Aujourd'hui, par simplicité (et couts?), on utilise l'environnement de staging à plusieurs fins. Demain dans l'idéal, il serait opportun d'avoir 2 environnements distincts ayant des buts plus précis :

### Env : staging

- Son but est d'assurer les mises en prod en ayant à disposition un environnement qui reproduit le plus fidèlement possible la prod y compris en terme de données.
- Le workflow classique de mise en prod :
  - 1. Dump de la DB de prod vers staging
  - 2. Push du code sur staging pour vérifications auto (CI) et manuelles
  - 3. Mise en prod (copie du code de staging vers la prod)
- ⚠️ dès lors que le staging contient des données réelles d'utilisateur, il ne doit plus envoyer d'email !

### Env : demo
Aussi appelé "sandbox" ou bac à sable

-------

Le respect des principes [12factor](https://12factor.net/) est très important pour assurer le cloisonnement stricte des différents environnements.

**Comment by alemangui** [comment]
D'accord avec ça. Env Démo à créer post ISO MVP
