### ISSUE TITLE
Améliorations/regressions pages auth

### ISSUE THREAD

**Issue by alemangui** [betagouv/complements-alimentaires#365]
- Gestion du query-param `next` (par exemple : `/login?next=nouvelle-demarche`) qui permet de spécifier la page à charger après le processus d'auth
- Les actions principales devraient être déclenchés par la touche "Entrer" (par ex le login dans la page login)
- Les pages auth (login, sign-up, etc) doivent faire une redirection vers la page d'accueil si l'utilisateur est déjà connecté

**Comment by ddahan** [comment]
> Gestion du query-param next

Pour faire côté Vue ce qu'on a avec Django ? Intéressant, j'avais pas pensé à ce moyen de faire.
Quels sont les avantages/inconvénients à mettre l'info dans l'URL directement, plutôt que dans une méthode selon toi ?

Exemple de ce que j'avais fait avec le logout :
```js
export const logOut = async (
  message = "Vous avez été déconnecté de la plateforme.",
  redirectRouteName = "LandingPage",
  routeQueryParams = {}
) => { ... }
```

> Les actions principales devraient être déclenchés par la touche "Entrer" (par ex le login dans la page login)

Est-ce qu'on est sûr de ça, par rapport à l'accessibilité ? (faut vraiment que je fasse la formation ^^)
Là tout de suite, il faut faire 2 fois tab et ensuite on peut appuyer sur "Enter".

> Les pages auth (login, sign-up, etc) doivent faire une redirection vers la page d'accueil si l'utilisateur est déjà connecté

Tout à fait, j'y pensais et j'attendais de voir le workflow qu'on choisit pour ça. Merci de m'y faire repenser.
Parfois sur certains sites typiquement si tu vas sur `login/` en étant déjà loggué, tu as un message : "vous êtes déjà connecté en tant que Toto, voulez vous continuer OU vous déloguer pour utiliser un autre user"

**Comment by alemangui** [comment]
Adressé ici : https://github.com/betagouv/complements-alimentaires/pull/804
