### ISSUE TITLE
Préparer onboarding utilisateurs nouvelle plateforme - Lancement de Compl'Alim 

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/complements-alimentaires#411]
- Rendre visible que ds le nouvel outil : plus besoin de choisir l'art de la procédure car dépend du statut de l'ingrédients et substances (article blog)

**Comment by Fantine-py** [comment]
Hello, je ferme cette PR car ça n'est pas directement lié au produit mais c'est plutôt un sujet de déploiement :)
