### ISSUE TITLE
rendre cliquables et cherchables les synonymes ?

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/complements-alimentaires#413]
ex : https://compl-alim.beta.gouv.fr/element/16--substance--anthraquinones

Dans cette substances, en synonymes il y a : 
Dérivés Hydroxyanthracéniques

qui est aussi une substance : https://compl-alim.beta.gouv.fr/element/135--substance--d%C3%A9riv%C3%A9s%20hydroxyanthrac%C3%A9niques

![Image](https://github.com/betagouv/complements-alimentaires/assets/36134318/d1cc5745-a800-4875-9cbc-eb6f69793315)

**Comment by pletelli** [comment]
Après réflexion, les synonymes qui dupliquent les substances ne devraient pas être présents comme synonymes (et donc pas de nécessité de les rendre cliquable).
Ce qu'il faut faire c'est une étape de nettoyage des synonymes à l'import.
Exemple du zinc :
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/55be1749-efe3-4e7f-95a9-23d80e66071b/0d890061-396b-4de2-811a-bb6d8cbd5a29/Untitled.png)

**Comment by pletelli** [comment]
Mais avec Anthraquinones et Dérivés hydroxyanthracéniques c'est un autre problème...
Ces 2 éléments existent en tant que substance (et sont liés à des plantes différentes...) si ce sont des synonymes exactes, il ne devraient en exister qu'un seul.
Je remonte l'info dans https://www.notion.so/betagouv-dinum/Les-incoh-rences-dans-la-base-de-donn-es-actuelles-0429cb634e884d83a7cfd94498899737 pour en discuter avec le BEPIAS
