### ISSUE TITLE
modélisation : poser à plat une base de données "propre" à partir de ce que l'on a et que l'on comprend

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/complements-alimentaires#421]
Intuitions de Perrine et Jenn : 
- remplacer éléments par "ingrédients" qui semblent être le mot-valise pour définir les diff formes d'apports (plantes, micro-org, additifs, auxilliaires techniques, arômes) + substances qui peuvent être ajouter en tant que tel

**Comment by JenniferStephan** [comment]
à toutes fins utiles, ce que, sans la BDD de teleicare, j'avais commencé à esquisser en recoupant les infos que je trouvais : 
dans l'arrêté de 2016
dans les listes CCRF de 2019 (les liens sont dans le figma)
avec l'intention de comprendre justement les nivellements entre 'ingrédients'/'substances'... 


https://www.figma.com/file/ppGMIGCqwBg0LHTcha5q6l/ingr%C3%A9dient-%2F-substances?type=whiteboard&node-id=0-1&t=wr9De9aXIMY296BK-0

**Comment by JenniferStephan** [comment]
coucou @pletelli tu penses que tu auras le temps de faire ça d'ici le séminaire pour en faire un atelier ?

**Comment by pletelli** [comment]
![Image](https://github.com/betagouv/complements-alimentaires/assets/1618987/4bc9a587-8b9e-4590-9b3b-3514c8a247bf)
![Image](https://github.com/betagouv/complements-alimentaires/assets/1618987/566126e0-1f0d-44ea-bb93-bf945bf00583)
