### ISSUE TITLE
Questionnement modélisation des rôles

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#468]
### Questionnement modélisation (à partager)

Après avoir pas mal travaillé sur les rôles et la gestion des collaborateurs, j’ai la forte intuition que notre modélisation n’est pas idéale avec les rôles. Je partage pour avoir un 2e avis. Voilà le déroulé de ma réflexion :

Aujourd’hui on ne fait pas la distinction entre les rôles “globaux” (ex futur : expert Anses) et les rôles liés à une entreprise (ex : déclarant, gestionnaire).

Quand on dit “les rôles liés à une entreprise”, cela signifie que le rôle n’a pas de sens en tant que tel, en étant juste lié à l’utilisateur. En effet, un utilisateur ne peut pas être juste “déclarant”. Il est déclarant pour le compte d’une ou plusieurs entreprises.

**1er problème**

Aujourd’hui, une situation qui n’a pas de sens (être déclarant sans entreprise) est d’un point de vue de la modélisation, possible. Par exemple, je me suis retrouvé dans ce cas là :

```python
In [9]: Declarant.objects.get(user=user).companies.all()
Out[9]: <CompanyQuerySet []> # J'attends plutôt un Declarant.DoesNotExist
```

Je n’aurais jamais voulu avoir ce cas possible. Bien-sur, on pourrait faire en sorte en faisant attention que ça n’arrive jamais, en supprimant l’objet s’il est vide. Mais c’est du travail et du risque en plus, pour pallier à une modélisation qui n’est pas idéale.

**2e problème**

Cette modélisation implique que tous les attributs de l’objet `Declarant` n’ont pas lieu d’être. Par exemple, un déclarant avec un champ `is_active` n'a pas de sens, car un déclarant n'est actif ou inactif que pour une entreprise donnée.

Cet attribut `is_active` (et potentiellement tous les autres de l'objet Declarant ou CompanySupervisor) devraient donc plutôt exister dans la through M2M entre le déclarant et la company, car ces attributs ont vocation à décrire le rôle **en lien avec l’entreprise, et non pas dans l’absolu.**

**3e problème**

Dur à expliquer factuellement, mais mon intuition que le code est pas très naturel et trop complexe à écrire pour un besoin relativement simple, cas typique d’une modélisation qui fit pas.

Ces 3 problèmes me font me rendre compte que la modélisation est incorrecte.

**Comment régler cela ?**

Il me semble qu’il est contreproductif d’avoir des objets qui ne contiennent qu’une M2M vers avec un attribut `companies`. On pourrait s’en débarrasser et simplifier de cette manière :

```python
class Company(models.Model):
    supervisors = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through="SupervisorRole",
        blank=True,
        verbose_name="gestionnaires",
        related_name="supervisable_companies",
    )
    declarants = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through="DeclarantRole",
        blank=True,
        verbose_name="déclarants",
        related_name="declarable_companies",
    )

class CompanyRole(Deactivable):
    class Meta:
        abstract = True
        unique_together = ("company", "user")
        
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class SupervisorRole(CompanyRole, models.Model):
    pass


class DeclarantRole(CompanyRole, models.Model):
    pass 
```

**Et pour l’accès aux rôles ?**

De ce cas, il découle le fait qu’il existe 2 notions très distinctes : les rôles, et les rôles par entreprise. Voilà comment on pourrait découper de manière cohérente :

- `user.global_roles()` → pour récupérer les rôles globaux liés à l’utilisateur lui-même (ex: [expert Anses])
- `user.company_roles(company_id)` → pour récupérer les rôles liés à une entreprise spécifique (ex : [déclarant pour Google])
- `user.roles(company_id)` → ça serait l’union des deux autres fonctions. (ex: [expert Anses, déclarant pour Google]). Ca correspond à la manière dont on voudrait afficher les infos sur le dashboard : par exemple si l’entreprise Google est sélectionnée, alors à ce moment, mes rôles disponibles sont expert Anses et déclarant.

**Comment by pletelli** [comment]
Merci d'avoir pris le temps de poser ça à plat.
Je n'ai rien contre cette proposition !


Et ça me fait penser à d'autres options (auquelles tu as peut-être déjà pensé, si oui, sorry) : 

* une modèlisation avec une rôle de déclarant toujours on par défaut :
```
class CompanyRole(Deactivable):
    class Meta:
        abstract = False
        unique_together = ("company", "user")
        
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)    
    is_supervisor = models.BooleanField()
```

* j'ai bien compris que tu voulais marquer clairement que les rôles d'instructions et rôles liés aux entp seraient différents, mais les instructrices auront peut-être une modélisation de Role un peu similaire (par défaut elles seront "autorisées à voir la déclaration" mais pas "assignées à une déclaration").

* Et ça me fait penser que le rôle _AnsesSomething_ sera aussi specifique à certains objets seulement  (une/des entreprises voire à une/des déclarations).

**Comment by ddahan** [comment]
Merci beaucoup @pletelli ! Du coup j'ai répondu en partie sur la PR en question.
Et pour les rôles futurs, j'avais la même chose en tête, à savoir qu'il est possible que pas mal de roles soient liés à des objets, auquel cas il se pourrait que chaque rôle corresponde à une classe avec ses attributs spécifiques, dans le cas le plus extrême. Ce qui ne me semble pas poser de souci particulier d'ailleurs.
