### ISSUE TITLE
Assigner à un type d'ingrédient une activité : les déclarants n'ont plus la possibilité de choisir

### ISSUE THREAD

**Issue by pletelli** [betagouv/complements-alimentaires#474]
# que signifie "actif" ou "inactif" ?
Pour moi c'était pour savoir si l'ingrédient avait un impact sur la santé. Mais en voyant que certains ingrédients qui dans la base de données de référence sont considérés comme "actif" mais qui sont déclarés "inactifs" lors de la déclaration, je doute de ma compréhension.
Par exemple "le bifidobacterium lactis inactivée" est souvent indiqué "inactif" dans les déclarations alors que inactivé ne veut pas dire inactif
https://www.processalimentaire.com/brevets/des-probiotiques-inactives-mais-toujours-efficaces-34568
https://www.anses.fr/fr/system/files/NUT-Ra-Preprobiotiq.pdf

En tout cas, il faudrait mettre une infobulle pour préciser ce que ça signifie.

# Revoir s'il est normal de permettre aux déclarants de modifier l'activité des ingrédients 
les passer de inactifs à actifs, par exemple le jus d'acérol
ou l'actifs à inactifs par exemple Acétate de rétinyle

**Comment by ddahan** [comment]
Une théorie sortie de mon invention : peut-être que l'activité dans le cadre d'une déclaration, concerne l'activité par rapport au but recherché par le produit. Genre une substance qui pourrait être active pour une crème solaire car elle aide a bloquer les rayons UV, mais inactive dans un autre produit.
