### ISSUE TITLE
Tester l'envoi d'emails dans les tests unitaires existants

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#511]
Actuellement dans mes tests unitaires (et peut-être d'autres), l'envoi de mails n'est pas testé.
Cela pourrait être intéressant de refaire une passe pour ajouter ces tests.
cf. https://github.com/betagouv/complements-alimentaires/pull/490#discussion_r1606999587

**Comment by alemangui** [comment]
Je me permet de le fermer suite à la discussion autour de Brevo
