### ISSUE TITLE
Lorsque je crée une entreprise, j'ai automatiquement le statut de gestionnaire + déclarant. 

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/complements-alimentaires#546]
j'ai testé de créér mon labo "dinum" avec toutes les infos
j'arrive sur mon tableau de bord et j'ai buggué en ne comprenant pas pq je ne pouvais pas cliquer sur "toutes mes déclas" et que je ne voyais pas la possibilit d'en créer une nouvelle

c'est en cliquant par hasard sur "collaborateurs" que j'ai vu que je n'avais pour le moment que le statut de 'gestionnaire' et pouvait m'auto-accorder le statut de "déclarant"

proposition : lorsque l'on est le seul gestionnaire d'une entreprise; auto-grant le statut de déclarant par défaut ? 

![Image](https://github.com/betagouv/complements-alimentaires/assets/36134318/532c8866-94b3-43d4-931c-eaaace51ee38)
![Image](https://github.com/betagouv/complements-alimentaires/assets/36134318/ee4abeb2-cb84-4881-8f15-3743df280c55)

**Comment by ddahan** [comment]
Merci @JenniferStephan , je vois bien le souci.
Je pense que la cause principale vient du fait que par défaut dans le workflow, à aucun moment on ne dit à ce nouvel utilisateur qu'il existe un système de "rôles". J'aurais pensé qu'avec la barre bleue, l'utilisateur le déduise :

![Image](https://github.com/betagouv/complements-alimentaires/assets/1933516/f48edff7-3294-4ea4-8676-375ada875976)

Mais en fait, non. Ou en tout cas, il n'y a rien qui dit qu'il existe un 2e rôle à ce moment, et donc en effet, pas évident de savoir qu'il y a une action à faire pour pouvoir déclarer.

Comme tu l'as dit, donner tous les rôles à un utilisateur qui est seul pourrait être une bonne solution, assez rapide à faire (il faut aussi changer un peu le wording). J'allais dire en inconvénient que ça "repousse" le problème car il sait toujours pas qu'il existe des rôles différents. Néanmoins il le découvrirait au moment de l'ajout d'un nouveau collaborateur (qui est le use case suivant le plus probable) : 

![Image](https://github.com/betagouv/complements-alimentaires/assets/1933516/918cd8f0-fea0-48ab-bd2c-3639af1de6c9)

Bref, en v1 ça m'a l'air d'être une bonne solution aussi. @alemangui ou @pletelli pour un 2e avis peut-être ?
