### ISSUE TITLE
Import de données plantes/ingrédients/etc

### ISSUE THREAD

**Issue by pletelli** [betagouv/complements-alimentaires#56]
- [x] Faire la commande pour l'import des csv dans les modèles
- [x] ajouter "from simple_history.models import HistoricalRecords"
- [x] intégration des fichiers CSV de relation (synonymes, parties de plantes, etc)
- [x] faire la recherche dans les synonymes
- [x] vérifier comment l'update est renseigné avec HistoricalRecords

**Comment by JenniferStephan** [comment]
Coucou, je mets ici des éléments empiriques des informations potentiellement trouvables dans le champ valise "commentaires privés" et "commentaires publics"; dans l'objectif d'extraire les données importantes et d'éventuellement les structurer :) 

Dans ce champ, on peut trouver : 

- des avis ANSES : https://www.anses.fr/fr/derniers-documents-mis-en-ligne 
du texte et une liste d'avertissements suivant le type de population

ex : ex : https://complements-alimentaires-staging.cleverapps.io/element/432--plante--Eucalyptus%20globulus%20Labill.

- des avis de la cartographie EMA : https://european-union.europa.eu/institutions-law-budget/institutions-and-bodies/search-all-eu-institutions-and-bodies/european-medicines-agency-ema_fr
même exemple qu'au dessus

- des interdictions liées au réglement union européenne avec un lien vers l'article de la réglementation (concerne uniquement une partie de la plante en général) 
ex : Les préparations de feuilles d'Aloe contenant des dérivés hydroxyanthracéniques sont interdites. (Règlement (UE) 2021/468) = https://complements-alimentaires-staging.cleverapps.io/element/93--plante--Aloe%20arborescens%20Mill.

- des avertissements suivant le type de population : 
ex : "L emploi chez les femmes enceintes et allaitantes ainsi que chez les personnes sous traitement antidépresseur est déconseillé." = https://complements-alimentaires-staging.cleverapps.io/element/381--plante--Griffonia%20simplicifolia%20(DC.)%20Baill.

- des infos complémentaires, des pièces jointes à inclure dans le dossier de déclaration pour justifier du bon dosage, de la fiche technique de la substance : 
ex : https://complements-alimentaires-staging.cleverapps.io/element/381--plante--Griffonia%20simplicifolia%20(DC.)%20Baill.
NB : info hyper utile pour les pros et pour les instructrices, pour moi, pourrait être un champ : "les éléments à ajouter au dossier" optionnel

- pour les "novel food", en général l'entrée d'une substance entrée dans le catalogue et ce changement de statut est marqué en texte avec un lien vers la réglementation qui le dit
https://food.ec.europa.eu/safety/novel-food/novel-food-status-catalogue_en
ex : https://complements-alimentaires-staging.cleverapps.io/element/806--substance--Extrait%20des%20racines%20de%20trois%20plantes

- précisions sur les allergènes potentielles 
- précisions sur le dosage max (ex : https://complements-alimentaires-staging.cleverapps.io/element/1137--ingredient--Acides%20gras%20c%C3%A9tyl%C3%A9s)
- des synonymes
ex : https://complements-alimentaires-staging.cleverapps.io/element/1059--ingredient--Extrait%20des%20racines%20de%20trois%20plantes

---------
à extraire de ce champ commentaire pour en faire de nouveaux; en vrac, selon moi : 
- présence d'allergène
- dosage min
- dosage max
- novel food (booléan) si oui, date d'entrée dans le catalogue et URL vers texte en question
- avertissements à mentionner sur l'étiquette
- avertissements sur les populations cibles
- avis ANSES et URL vers le lien de l'avis; sa date; les mises à jour
- avis EMA
- les synonymes (déjà présent dans la base, mais alimenter ce champ à partir des infos contenues dans comm)

**Comment by pletelli** [comment]
Merci ça aide que tu ais dégrossi ça, j'avais tout sauf les synonymes.

Pour l'instant pour une idée des chiffres dans le champ commentaire public (tout ingrédients confondus):
* 72 mentions de "anses"
* 29 urls
* 67 mentions "ema"
* 38 mentions à des allergènes
* 53 mentions novel food

**Comment by pletelli** [comment]
Idée de niveau de gravité 


![Image](https://github.com/betagouv/complements-alimentaires/assets/1618987/2e256184-b211-41b9-8cb9-3d29a16f52c9)
