### ISSUE TITLE
Faut-il garder les onglets "Accueil" et "Entreprises" lorsque le déclarant est connecté ?

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#621]

**Comment by alemangui** [comment]
Selon moi non, même en mode déconnecté on peut challenger le wording de ces onglets

**Comment by Fantine-py** [comment]
*A discuter avec l'équipe + la designeuse, mais pour ne pas oublier je note
ici mes idées/ remarques : *

   - Plateforme d'instruction  :
      - Je pense que le "tableau de bord" devrait renvoyer à la vue "liste
      des déclarations" (qu'on soit instructeur ou viseur).
      - Eventuellement, créer un second onglet "paramètres" ou "mon compte"
      pour accéder à la gestion du compte utilisateur.


   - Plateforme générale (peu importe interface déclaration (connecté ou
   non)/ interface d'instruction) :
      - Onglet "Entreprise" - remplacer le wording par : "vérifier un
      ingrédient " ? "chercher un ingrédient" ? "base ingrédients" ? "base de
      données" ?



*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***


Le lun. 22 juil. 2024 à 10:44, Fantine Monot ***@***.***> a
écrit :

> Oui je suis d'accord ! On va demander conseil à la designeuse :)
> *Fantine Monot*
> Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
> *fr*
> 06 32 32 89 82
> ***@***.***
>
>
> Le lun. 8 juil. 2024 à 15:25, Alejandro M Guillén <
