### ISSUE TITLE
tableau de bord instruction : besoin de sélectionner des lettres pour filtrer les dossiers qui apparaissent 

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#624]
@alemangui est-ce qu'il serait possible de faire une barre de recherche comme cela ? Parce que j'ai peur que des cases à cocher ce soit très chronophage... 

On leur laisserait la possibilité de : 

- sélectionner des lettres discontinues avec une virgule
- filtrer entre 2 lettres avec un tiret

![Image](https://github.com/betagouv/complements-alimentaires/assets/61788694/6d2c4d48-c680-4790-8a15-0e3d4c1609dc)

**Comment by pletelli** [comment]
à discuter avec la designeuse

**Comment by Fantine-py** [comment]
j'archive ce ticket et crée un nouveau ticket pour sortir les stats sur les dossiers pour début septembre @pletelli (@alemangui pour info)
