### ISSUE TITLE
staging plateforme déclaration : le menu déroulant pour la forme lidique ne fonctionne pas

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#625]
Bonus :  ce serait bien d'adapter les choix du menu déroulant selon la forme "liquide" / "solide" ?

**Comment by alemangui** [comment]
@pletelli celui-ci si on refait un import des données en staging ça se fix non ?

**Comment by Fantine-py** [comment]
hello, je ne sais pas si vous avez refait un import depuis mais ça ne fonctionne toujours pas @alemangui  :(

**Comment by pletelli** [comment]
jusqu'à maintenant ça se défini dans l'admin https://compl-alim.beta.gouv.fr/admin/data/galenicformulation/ car ce n'était pas une donnée existante dans TeleIcare.
Donc je l'ai fixé, mais avec la déduplication des substances / ingrédients je vais intégrer un outil de transformation après l'import des données TeleIcare. à suivre pour un fix plus long terme
