### ISSUE TITLE
Interface pro : amélioration du process de validation des étapes de complétion du formulaire de déclaration 

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#626]
ce serait mieux en termes d'expé utilisateur d'être bloqué d'être l'étape 1 plutôt que de devoir revenir en arrière après avoir essayé de soumettre. 

![Image](https://github.com/betagouv/complements-alimentaires/assets/61788694/6cccce92-9689-449c-a508-3457f505638c)

**Comment by alemangui** [comment]
T'en penses quoi d'éventuellement montrer ces soucis dans l'onglet _résumé_ avant de soumettre la démarche ?

Je dis ça car ça pourrait être embêtant de ne pas pouvoir remplir un autre champ car on bloqué sur une étape. Par exemple, si le déclarant veut ajouter une pièce jointe d'un analyse labo, mais ne se souviens pas de l'unité de mesure (ou un autre champ obligatoire de la première étape) ça serait pas top qu'iel ne puisse pas le faire.

En écrivant ça peut-être que l'approche onglet aussi dans cette page serait préférable... :thinking:

**Comment by Fantine-py** [comment]
Hello, 2 remarques :

   - Serait-ce possible de mettre un lien ancre pour que s'ils cliquent sur
   l'erreur "forme galénique ne peut pas être vide", ça les emmène directement
   dans l'onglet "Le produit" et au bon endroit sur la page ?

[image: image.png]


   - Possible aussi de mettre en rouge les champs manquants dans l'onglet
   "Le produit" ? Par exemple "forme galénique" dans notre exemple ?

[image: image.png]


*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***

**Comment by Fantine-py** [comment]
Je remets ici mon commentaire, car les images ne passent pas quand je réponds directement depuis ma messagerie ! 
---

Hello, 2 remarques : 

- Serait-ce possible de mettre un lien ancre pour que s'ils cliquent sur l'erreur "forme galénique ne peut pas être vide", ça les emmène directement dans l'onglet "Le produit" et au bon endroit sur la page ? 

![Image](https://github.com/user-attachments/assets/d1892644-bb82-4830-ae74-8df10854ecf3)

- Possible aussi de mettre en rouge les champs manquants dans l'onglet "Le produit" ? Par exemple "forme galénique" dans notre exemple ? 

![Image](https://github.com/user-attachments/assets/5b6e33ae-21bb-4fb5-b4ed-e73bcd55b4f8)

**Comment by pletelli** [comment]
# Petits fix
On indique les champs obligatoires avec l'* #702 + #627
On ajoute un bouton "Sauvegarder et continuer vers le prochain onglet"

# Meilleure lisibilité des erreurs
On ne bloque pas le passage d'un onglet à l'autre.
On met le lien vers le bon onglet dans la box rouge
On fait une unique box par onglet.
Le front doit connaître le mapping entre les champs back et les onglets côté front.

# Feature en plus
On rend bloquant la dose max dépassée (validation côté back)

**Comment by Fantine-py** [comment]
Hello @alemangui, normalement un message devrait s'afficher si le déclarant saisi une dose > dose max car on tombe dans le champ des articles 17/18. Ca rejoint ce ticket créé par @pletelli [#747](https://github.com/betagouv/complements-alimentaires/issues/747)
