### ISSUE TITLE
staging instruction : si l'instructeur autorise la déclaration et met un commentaire à destination de l'administration, où est-ce que ce commentaire apparait ?

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#646]
car il n'est pas visible dans l'historique (même en tant qu'instructeur)

**Comment by alemangui** [comment]
À ajouter dans l'écran d'instruction/visa pour les déclarations read-only
![image](https://github.com/betagouv/complements-alimentaires/assets/1225929/dbb77639-6231-4215-982b-7d6e1af02827)
