### ISSUE TITLE
staging instruction : en tant que viseur, je n'ai pas à voir les déclarations qui n'ont pas besoin d'être visées (MAJ le filtre)

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#648]
![Image](https://github.com/betagouv/complements-alimentaires/assets/61788694/88ab25a9-162f-4991-8e16-48c11d23f9f3)

**Comment by alemangui** [comment]
La viseuse devrait pouvoir voir les déclarations en instruction - pas possible aujourd'hui car 403 si on n'a pas les deux rôles.
