### ISSUE TITLE
en tant que déclarant, je reçois une notification par mail pour m'informer sur l'avancée de mon dossier

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#653]
- Passer par brevo pour la V1

**Comment by Fantine-py** [comment]
Hello @alemangui, si on peut l'avoir pour le MVP ce serait top (en passant par Brevo). Ca te semble jouable ?

**Comment by alemangui** [comment]
Oui tout à fait jouable. Si ça te va on se fait une petite session en visio pour mettre en place les templates Brevo qui seront utilisés ? Comme ça après je peux me connecter directement pour l'envoi automatique.

**Comment by Fantine-py** [comment]
Oui parfait ! Demain aprem avant 16h ou jeudi ?

*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***
