### ISSUE TITLE
Plateforme d'instruction : revoir l'ordre de présentation des infos dans la section "informations sur le produit"

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#676]
Section « Informations sur le produit », modifier comme suit l’ordre des catégories : 
1. Nom 
2. Marque
3. Description
4. Population cible 
5. Forme galénique
6. Mode d’emploi 
7. Unité de consommation 
7. DJR 
8. Conditionnement 
9. DLUO

Supprimer la mention de l'arôme.

**Comment by pletelli** [comment]
Pour info, cette modif impacte aussi la présentation des infos sur le produits dans l'interface de déclaration.
Mais ça me semble pertinent dans les 2 cas.
