### ISSUE TITLE
Plateforme d'instruction : dans la section "infos sur le produit", préciser l'unité de mesure pour la DJR

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#677]
Parce que si c'est une forme solide, un comprimé ou une gélule par exemple, s'il est indiqué "1" pour la section "unité de consommation", on comprend aisément que c'est 1 comprimé. En revanche, si c'est une forme liquide, ça ne fonctionne pas : "1" de quoi ? 1 mL, cL etc.

**Comment by pletelli** [comment]
c'est pas "ampoule"/"bouchon" ?
Parce que le "Poids/ volume d'une unité de consommation" est spécifié ailleurs

**Comment by Fantine-py** [comment]
Hum, dans ce cas là il faudrait qu'on ajoute des infobulles pour préciser
la définition, car Mireille et moi avions compris que : "*unité de
consommation =  volume/poids d'1 dose"* ! Où est mentionné le poids/volume
d'une unité de consommation dans ce cas ?

*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***


Le jeu. 18 juil. 2024 à 17:52, Perrine L. ***@***.***> a
écrit :

**Comment by pletelli** [comment]
![image](https://github.com/user-attachments/assets/56dd994d-cbee-4513-b756-b62685ea5a25)
![image](https://github.com/user-attachments/assets/7f0fe0da-d468-4a17-8335-2a3adad6d89e)
Est-ce qu'on peut s'en parler de vive voix.
Car j'ai l'impression qu'il y a qqch à simplifier ici, mais je ne suis pas sûre de comprendre votre raisonnement à toi et Mireille ?
Mercredi matin ?

**Comment by Fantine-py** [comment]
Hello Perrine,

Oui parfait pour mercredi :) Après notre point avec le SICCRF ?

*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***


Le lun. 22 juil. 2024 à 18:44, Perrine L. ***@***.***> a
écrit :

**Comment by Fantine-py** [comment]
En fait @pletelli j'ai compris d'où vient notre incompréhension : côté BEPIAS, par dose journalière recommandée ils ont en tête le volume total à prendre par jour (pour vérifier qu'on ne dépasse pas les doses maximales). 

Dans l'exemple ci-dessus, ce serait 12*3 = 36ml (à la place de "3 doses"). Or le problème du champ libre, c'est le risque que le pro mette juste "36" et du coup, dans la déclaration soumise au BEPIAS, l'instructrice n'a pas l'info de si le pro a bien en tête 36ml et non pas 36 doses (et dans ce cas de figure, on dépasserait la dose journalière maximale autorisée). 

Donc idéalement il faudrait demander au pro de renseigner 36 + préciser "ml". Ou alors de reprendre automatiquement l'unité de mesure qu'il aura sélectionné en renseignant le poids d'une unité de consommation.
