### ISSUE TITLE
Plateforme d'instruction : modifier la liste des motifs d'irrecevabilité d'un dossier

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#684]
Ajouter les motifs suivants dans la section « le dossier n’est pas recevable »

```[tasklist]
##### Motifs  :
- [ ] « Absence ou non conformité de l’étiquetage »
- [ ] « Absence de preuve de reconnaissance mutuelle »
```
	
Par ailleurs, se pose la question de supprimer la catégorie de motifs « le CA n’est pas acceptable »  car le seul motif qu’on garderait ici serait « existence d’un risque », tous les autres motifs relèvent d’un problème d’irrecevabilité du dossier finalement. 

Mais Mireille me disait que  souvent, lorsqu’il y a un pb inhérent au CA c’est parce qu’il va être assimilé à un médicament ou qu’il y a un problème de surdosage et il existe des motifs plus hauts dédiés pour ces cas de figure. Aussi, @pletelli, pourrais-tu regarder à l'occasion si ce motif a déjà été utilisé dans Teleicare ? :)

**Comment by pletelli** [comment]
Coucou, on avait déjà un peu parlé de ça ici https://github.com/betagouv/complements-alimentaires/pull/515

Les 2 motifs avaient été supprimés dans un objectif de simplifier cette liste.

Et du coup ta demande rejoint cette issue que j'avais créée à ce moment https://github.com/betagouv/complements-alimentaires/issues/531 : nécessité de faire des stats pour savoir si ces motifs sont utilisés.

Je fais ça pour que tu puisses avoir un support de discussion avec Elodie mercredi du coup :)

**Comment by alemangui** [comment]
Ces deux raisons sont déjà dans la section en dessous, du coup on peut les bouger de catégorie sans problème.

J'attends du coup confirmation pour garder seulement _existence d’un risque_ dans la catégorie _Le complément alimentaire n'est pas acceptable_ ou je peux le faire dès maintenant ?

![image](https://github.com/user-attachments/assets/cbeb21e0-4529-4745-a613-9ecd83d7ce84)

**Comment by Fantine-py** [comment]
Coucou,

Tu peux le faire dès maintenant :)


*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***
