### ISSUE TITLE
Plateforme d'instruction/ déclaration : respecter la mise en forme du texte (commentaire du déclarant/ commentaire de l'instructeur).

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#686]
Aujourd'hui la mise en forme du texte (faite par l'instructeur par exemple) n'est pas respectée. Dans l'exemple ci-joint j'avais fait un saut à la ligne pour chaque tiret mais ça n'apparait pas comme cela dans l'historique. Cela peut poser problème car parfois les commentaires des instructrices sont très longs et il est donc nécessaire d'avoir une mise en page structurée et aérée pour s'y retrouver, plutôt qu'un très long commentaire en 1 bloc. 

A minima : 
- respecter les sauts de ligne

Si possible : 
- option "gras"  
-  option "italique"

![Image](https://github.com/user-attachments/assets/5f7fa637-f147-490f-bf5b-4eaeb5994e76)

**Comment by pletelli** [comment]
La mise en forme est bien conservée en base.
J'ajoute juste la gestion des sauts de lignes et la merge pour mercredi.

Pour les options "gras" et "italique", ça pourrait être pas mal d'utiliser marked.js pour compiler du markdown en html.
J'ai l'impression que ça serait dans une forme de compatibilité avec les messageries instantannées (Tchap) que de toutes façons les instructrices sont vouées à utiliser et connaître ?

Qu'en pensez vous @alemangui et @Fantine-py

**Comment by Fantine-py** [comment]
Hello,

Si on a déjà la gestion des sauts de lignes et la merge c'est très bien !

Je ne comprends pas bien ce que ça implique pour les instructrices d' "utiliser
marked.js pour compiler du markdown en html" ? :)

*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***


Le ven. 19 juil. 2024 à 17:21, Perrine L. ***@***.***> a
écrit :

**Comment by pletelli** [comment]
Coucou, 

Pour le markdown ça implique :
* que les chargées de mission apprennent le "language markdown" 
 * entourer un texte de * pour mettre en italique
 * entourer un texte de 2 ** pour mettre en gras
 * commencer un titre par #, etc
 
 
 Exemple
*italique*
**gras**
# Titre 1
## Titre 2

**Comment by alemangui** [comment]
@pletelli je pense que ce ne sera pas super simple la prise en main du Markdown pour les instructrices, mais je peux me tromper. Ça vous irait si on fix les retours à la ligne pour septembre et on voit éventuellement l'usage d'un WYSIWYG pour après MVP ?

**Comment by Fantine-py** [comment]
C'est bon pour moi !

*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***
