### ISSUE TITLE
Plateforme déclaration : indiquer par une asterix * les champs obligatoires à compléter dans la déclaration de mise sur le marché d'un CA.

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#702]
- [ ] forme galénique 
- [ ] Poids ou volume d'une unité de consommation (+ "unité de mesure" qui est liée)

**Comment by alemangui** [comment]
J'en profiterai pour corriger le fait que la description n'est pas obligatoire (alors que sur compl'alim on l'a signalé comme tel).
