### ISSUE TITLE
Distinguer automatiquement les déclarations rentrant dans le champ de l'article 15 Vs article 16 

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#707]
Ne pas tenir compte ici des critères de vigilance pour "article 15" (ça aura un impact sur le traitement de ces déclarations mais ça ne change rien au fait qu'elles soient dans le scope de l'article 15). 

### Règle - Article 15

Un complément alimentaire rentre dans le champ de l’article 15 si (critères cumulatifs) : 

(1) il est composé uniquement :

- d’ingrédients/substances “autorisés” en base
- OU d’ingrédients/substances non listées en base mais qui disposent d’un historique de conso
- OU d’ingrédients/substances non listées en base mais sont des novel food autorisés

(2) ET pas de dépassement d’une dose max (qtté substance A < dose max substance A) 

*NB : dans notre base, les ingrédients ayant le statut “autorisé” sont ceux issus des plantes/substances à but nutri ou physiologique/nutriments qui figurent dans les arrêtés français et selon les préconisations d'emploi dont la dose max ; ou sur les listes établies par la DGCCRF ; ou les plantes disposant en Europe d'un historique de consommation avant mai 1997 (conformément à l'article 4-3° du décret n°352-2006 du 20 mars 2006).*

### Règle - Article 16

Un complément alimentaire rentre dans le champ de l’article 16 si (critères cumulatifs ) :

(1) il est composé d’au moins un ingrédient/substance non autorisé/ non inscrit dans notre base de données

(2) ET le professionnel est en mesure de prouver que cet ingrédient/substance est légalement fabriqué/ autorisé dans un autre Etat membre ou pays partie de l'accord sur l'EEE (preuve de reconnaissance mutuelle).

**Comment by Fantine-py** [comment]
Je vais créer un doc Notion pour essayer de lister les règles/critères pour déterminer si une déclaration rentre dans le champ de l'article 15 / article 15 vigilance / article 16, pour qu'on puisse en discuter en asynchrone avec le BEPIAS @alemangui @pletelli

**Comment by Fantine-py** [comment]
Le lien vers Miro : https://miro.com/app/board/uXjVK1hWON8=/ 
Le lien vers Notion : https://www.notion.so/betagouv-dinum/Distinction-article-15-article-16-b5e365e834bf4197945ccb6b4d12bd4a

**Comment by Fantine-py** [comment]
Hello, en y repensant @pletelli et @alemangui, je me demande si le step 1 (avoir un algo de classification automatique des déclarations article 15/ article 16) n'est pas nécessaire pour le lancement du MVP ? En effet, le contenu de l'attestation de déclaration envoyée par le BEPIAS varie selon qu'on soit dans le champ de l'article 15 ou de l'article 16. Donc il faudra que les instructrices aient accès à cette info (sachant que comme on se le disait hier, en vrai elles ne vont pas instruire de dossiers sur Compl'Alim donc plutôt échéance mi-octobre). 

Ou alors il faut a minima qu'on demande aux pros au moment où ils renseignent leur déclaration de préciser s'ils sont dans le champ de l'article 15 ou de l'article 16. 

Qu'en pensez-vous ?

**Comment by Fantine-py** [comment]
Comme vu ensemble @pletelli, je le passe en MVP de la muerte

**Comment by Fantine-py** [comment]
![Image](https://github.com/user-attachments/assets/0c8797e9-ef1a-4cd0-b49f-ddfc9a5dee75)

**Comment by Fantine-py** [comment]
Juste pour garder un historique, je remets ici les commentaires du BEPIAS extraits du doc "expression des besoins" :  
- "_Lors de saisie de teneur supérieures à celles imposées dans la réglementation nationale / listes et tables mises à jour dans l’outil, que l’outil empêche la poursuite de la saisine procédure « article 15 » en indiquant que cela nécessite une procédure article 16 ou 17 ou 18._"
- "_Lorsqu’un produit a été déclaré à tort sous la procédure de « l’article 16 », il faudrait que le BEPIAS puisse réorienter le dossier en procédure de « l’article 15 » et poursuivre l’instruction => gain de temps pour l’administration comme pour le déclarant et que le télédéclarant puisse changer de procédure sans avoir à resaisir tous les éléments de la télédéclaration. Idem lors de saisie « déclaration » qui serait bloquée (car nécessite une autorisation article 16, 17 ou 18)._" 

--> tout sera réglé par la détection automatique par Compl'Alim de l'article auquel doit être rattaché le dossier déposé par le pro.

**Comment by pletelli** [comment]
Résumé du Notion sur les critères pour article 15 "vigilance" : 

* Plantes dont le champ `name` se trouve dans [Cannabis sativa, Griffonia, Curcuma, Aloe*, Rhamnus frangula, Rhamnus purshiana,  Cassia senna, Rheum palmatum, Rheum officinale, Camellia sinensis ]
* Substances dont le champ `name` se trouve dans [Melatonine, Glucosamine, Chondroïtine]

* si c'est des micro-organisme dont le champ `name`  dans [ Monascus purpureus]
* si la population cible se trouve dans [enceintes, femme allaitante, - 18 ans]
* si la forme galénique = jus ou autre

**Comment by Fantine-py** [comment]
Cette issue est finie non @alemangui @pletelli ? Je le ferme mais n'hésitez pas à réouvrir si vous n'êtes pas OK. J'en crée une nouvelle pour la détection des articles 15 nécessitant une instruction obligatoire (article 15 vigilance).
