### ISSUE TITLE
plateforme d'instruction - mettre l'adresse postale indiquée de l'étiquette sur l'onglet "Produit"

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#721]
Un point de contrôle important côté BEPIAS c'est de s'assurer que l'adresse postale indiquée sur l'étiquette du CA est bien la même que celle de l'entreprise qui commercialise le CA. 

Donc ce serait cool si on pouvait faire en sorte qu'elle "saute aux yeux" quand on arrive sur l'onglet "identité" :) 

Peut-être : 
- mettre en premier la section "Entreprise" avant la section "Déclarant ou déclarante" 
- indiquer l'adresse postale directement après le nom de l'entreprise et pas à la fin de la section 
- toute autre idée est bienvenue :)

![Image](https://github.com/user-attachments/assets/a814d6df-adcc-4663-82c6-aba98b3bcc55)

**Comment by pletelli** [comment]
Ajouter l'adresse d'étiquettage dans l'onglet "Produit" de l'instruction, juste au dessus de l'étiquettage (PJ).
