### ISSUE TITLE
MAJ des données objectifs/effets + population à risque

### ISSUE THREAD

**Issue by pletelli** [betagouv/complements-alimentaires#731]

**Comment by Fantine-py** [comment]
@pletelli @alemangui il faudrait rendre obligatoire le fait pour les pros de préciser les publics pour qui le CA est déconseillé (cf. ce commentaire du BEPIAS dans la liste au père-noël : “Indiquer certains éléments comme obligatoire à remplir, comme le fait que le complément alimentaire soit destiné/déconseillé à des jeunes enfants / femmes enceintes).

**Comment by pletelli** [comment]
La même issue suffit j'ajoute ça à ma TODO des jours qui viennent.

**Comment by pletelli** [comment]
Pour le public cible, on peut rendre le champ obligatoire notamment car on a en choix possible "Population générale"
Cependant pour les populations à risque, j'imagine qu'il existe des CA qui ne sont à risque pour aucune population. Difficile de le rendre obligatoire du coup. Qu'en penses-tu @Fantine-py ?
