### ISSUE TITLE
data : sortir les stats du nb de dossiers/ lettre pour la répartition entre les instructrices

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#754]

**Comment by pletelli** [comment]
![image](https://github.com/user-attachments/assets/eaaf92ee-0c30-4c1b-9a5b-d063ceb1b81c)

**Comment by pletelli** [comment]
à retrouver sur le dashboard Entreprise
https://compl-alim-metabase.cleverapps.io/dashboard/6-declarations?tab=23-entreprises
