### ISSUE TITLE
Ajouter le motif de refus suivant “Demande en article 17 attendue” (dans la section "Les procédures ne sont pas respectées")

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#790]

**Comment by alemangui** [comment]
Adressé en #801 

J'en ai profité pour faire un mini re-wording des raisons « Médicament par fonction »  et « Médicament par présentation ». Avant c'était seulement « Par fonction » et « Par présentation » ; dans cette vue ça avait du sens car on a le titre en haut, mais ailleurs dans l'application c'est mieux si on a un peu plus de contexte écrit - notamment dans la page viseuse.
