### ISSUE TITLE
Décision : décocher par défaut le visa décoché lorsqu'il s'agit d'une OBSERVATION (mais laisser à l'instructrice la possibilité de le cocher).

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#791]
Car Emmanuelle ne veut pas que les instructrices lui demandent systématiquement de viser leurs observations.

**Comment by hfroot** [comment]
est-ce que c'est déjà fait ?

![Screenshot 2024-10-31 at 13-04-07 Instruction - Compl'Alim](https://github.com/user-attachments/assets/4ae2d219-2293-4dd8-8817-79aadfb2d4b3)

**Comment by HeleneDubourdieu** [comment]
Oui c'est déjà fait
