### ISSUE TITLE
En tant qu'instructeur, j'ai besoin que le champ où je détaille ma décision (motivation) s'adapte automatiquement à la taille de mon commentaire sinon c'est compliqué pour me relire.

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#792]
https://www.loom.com/share/e59951d07b194c37b3eb8a4b98c5db59?sid=e0f51d40-2a64-482b-bf40-2882f6be7e9d

**Comment by alemangui** [comment]
@Fantine-py peux-je challenger le milestone de celui-ci ? :angel:

**Comment by alemangui** [comment]
Aujourd'hui c'est possible de redimensionner le champ de text `textarea`

![image](https://github.com/user-attachments/assets/04eeb50e-8d99-4e12-94f3-0553940f1050)
