### ISSUE TITLE
En tant que viseur, j'ai besoin de connaître le motif de refus de l'instructeur

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#793]
Entretien Emmanuelle : 
- besoin de savoir pourquoi l'instructrice a émis une observation/objection/refus (le ou les motif.s de refus coché.s) 
- auj. on a slment l'info qu'une observation a été émise (cf. capture d'écran ci-dessous)

![Image](https://github.com/user-attachments/assets/1b643947-1d9e-4e99-9ec7-a0a70c8ddebf)

**Comment by alemangui** [comment]
@Fantine-py pour voir ce fix il faudra ré-instruire les dossiers en leur donnant une ou plusieurs raisons avant de les repasser pour visa.

**Comment by Fantine-py** [comment]
Ok super, merci

*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***
