### ISSUE TITLE
En tant qu'instructeur ou viseur, je dois pouvoir me ré-assigner un dossier actuellement traité par une autre personne (sans validation par cette personne)

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#794]
Entretien Emmanuelle.
Il faut que les instructrices puissent récupérer les dossiers de X si elle est en vacances et que le déclarant a besoin d'une réponse urgente, si X est malade etc. La réassignation doit donc pouvoir se faire sans que X valide.

**Comment by alemangui** [comment]
J'ai fait un fix rapide qui permet de débloquer cette situation sur ce commit : 36ef35a6f1c8b495aee93b8066ae273210e0d9d5

### 1. Lors que la déclaration revient de visa / observation et est en état « en attente d'instruction »
Un message est affiché pour proposer à l'instructrice connecté de reprendre le dossier. Démo ci-dessous :

https://github.com/user-attachments/assets/978057e1-14c0-49e3-a121-bd62ba2cd6ed

### 2. Lors que la déclaration est « en cours d'instruction »
Une autre instructrice peut quand même la reprendre et l’instruire, même si cette personne n'est pas assignée à la déclaration. Démo ci-dessous :

https://github.com/user-attachments/assets/4ff9df6d-864e-45b4-bc64-fbb306d93550

**Comment by alemangui** [comment]
@Fantine-py Suite à ce fix je me permets de le fermer. N'hésite pas à le rouvrir si la solution ne te convient pas ou si tu voudrais que dans le second cas ça soit plus explicite la reprise du dossier.
