### ISSUE TITLE
En tant qu'instructeur/viseur, j'ai besoin de connaître le délai qu'il me reste pour répondre

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#795]
D'un point de vue réglementaire, l'administration doit répondre dans un délai de 2 mois max pour les déclarations faites au titre de l'article 16. Si le pro ne reçoit pas de réponse de l'administration au bout de 2 mois, son silence vaut accord.
 
En revanche pas de délai fixé réglementairement pour les déclarations article 15. 

Les instructrices/viseurs ont donc besoin de cette info pour prioriser le traitement de leurs différents dossiers. --> Je pense qu'il faudrait le mettre dès le tableau avec la liste des déclarations (**elles ont cette info dans Teleicare**). 

Peut-être remplacer la colonne "date de modification" par "date limite de réponse" ? Avec possibilité de trier sur cette colonne. 

Il faut donc qu'apparaisse au niveau de la liste des déclarations : 
- l'article auquel se rattache un dossier
- le délai qu'il reste à l'administration pour répondre

**Comment by alemangui** [comment]
Est-ce que ces deux mois comptent à partir de la date de la première soumission du dossier ? Ou de la dernière ? 

Çad, si un dossier et soumis le 1er septembre, puis re-soumis suite à une observation le 1 octobre, la date limite serait _septembre + 2 mois_, ou _octobre + 2 mois_ ?

**Comment by Fantine-py** [comment]
@alemangui le compteur se réinitialise dès que le BEPIAS demande des infos complémentaires :) Donc dans l'exemple ci-dessus, la date limtie serait octobre + 2 mois

**Comment by alemangui** [comment]
Je te propose que dans les tables _instructrice_ et _viseuse_ on montre le temps écoulé depuis que le producteur a soumis (ou re-soumis) la déclaration.

Par exemple pour la table instructrice : (le texte de l'entête est nul mais c'est juste pour illustrer) 

| Nom du produit   | Entreprise             | État        | Soumis le | Instruit par
|----------------|--------------------|--------------------|--------------------|--------------------|
| Vitamine B12        | NutriVit | En cours d'instruction |  23 juillet (il y a 3 semaines) | Alejandro MG

Et pareil pour la table _viseuse_

| Nom du produit   | Entreprise             | État        | Date de soumission ou modification | Visé par
|----------------|--------------------|--------------------|--------------------|--------------------|
| Vitamine B12        | NutriVit | En cours d'instruction |  23 juillet (il y a 3 semaines) | Alejandro MG

**Comment by Fantine-py** [comment]
@alemangui j'y pense : il faudrait permettre aux instructrices de faire un tri sur cette future colonne (pour afficher en premier les dossiers qui se périment bientôt)

**Comment by Fantine-py** [comment]
Hello @alemangui comme discuté je me demande si un compteur ne serait pas plus parlant (Délai pour répondre : 24 jours) ? Mais je laisse @amandinegueg nous dire :) Sinon je préfère l'option 1 avec la date limite de réponse ! 

Et ça me fait penser qu'il faut non seulement qu'apparaisse dans ce tableau la date limite de réponse MAIS aussi l'article auquel se rattache la déclaration. J'ai créé la PR associée du coup. #827

**Comment by amandinegueg** [comment]
Hello, en effet, l'option 1 me parait la plus pertinente et droit au but. On peut aussi ajouter des tags automatiques ? A 5 jours de la date limite un tag urgent apparait.

**Comment by alemangui** [comment]
Top, du coup on part sur l'option 1  :+1: 

Le tag "urgent" pourrait venir après deadline de la muerte si ça vous va
