### ISSUE TITLE
En tant qu'instructeur, j'ai besoin de pouvoir distinguer facilement dans la liste des déclarations les dossiers où la viseuse m'a répondu. 

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#796]
Entretien Emmanuelle (50mn). 

Elles ont besoin de pouvoir distinguer ces 2 cas de figure car les dossiers où la viseuse a répondu vont être très rapides à traiter, puisqu'Emmanuelle indique aux instructrices la marche à suivre. Donc ça permet aux instructrices de rapidement évacuer ces dossiers. 

**C'est surtout important pour les dossiers où la viseuse s'est opposée à la décision de l'instructrice.** 

En revanche, un dossier nouvellement déposé par un pro va nécessiter un temps d'instruction plus long. 
**Ticket à relier à la PR sur le pv d'instruction du viseur (peut-être que ce besoin va disparaître ?)** #617

**Comment by Fantine-py** [comment]
@alemangui, où va aujourd'hui un dossier où le viseur "autorise" le complément ?

**Comment by Fantine-py** [comment]
J'ajoute ici les commentaires du BEPIAS extrait du doc "expression des besoins" : 
- "_Dans l'onglet "je consulte toutes les décla à examiner", il y tous les dossiers, les nouveaux jamais vus et les retours d'objections/observations._"
- "_Dans l'onglet "mes dossiers en cours", il y a ceux qu'on a ouvert (sans forcément les traiter, donc y compris ceux pris par erreur) + les retours d'observations mais pas les retours d'objections qui reviennent dans le pool commun => idéalement, il faudrait qu'on ait les retours des Pro sur "nos" dossiers, peu importe que notre remarque initiale ait été faite en observation ou objection_".

**Comment by Fantine-py** [comment]
en fait je ferme cette issue car ce sera résolu avec cette PR #826 @alemangui @amandinegueg

**Comment by Fantine-py** [comment]
en fait je ferme cette issue car ça va être résolu avec les droits d'instruction donnés au viseur https://github.com/betagouv/complements-alimentaires/issues/617 @alemangui @amandinegueg

**Comment by pletelli** [comment]
Je crois que je ne comprends pas en quoi #617 fait qu'on n'a plus besoin d'avoir un affichage différent pour les dossiers à instruire et les dossier avec retour de visa (plus rapides).
ça reviendrait à dire que la viseuse fait ses commentaires pour une instruction différente et fait elle même cette instruction différente ?

**Comment by Fantine-py** [comment]
Oui c'est ça !

En fait, il y a 2 cas de figure :
- soit la viseuse est alignée avec la décision proposée par l'instructrice,
auquel cas elle peut "confirmer" cette décision qui est alors envoyée au
déclarant (déjà le cas auj.)
- soit la viseuse n'est pas d'accord avec la décision proposée par
l'instructrice, auquel cas elle va écrire un commentaire pour expliquer à
l'instructrice pourquoi son avis diverge et dicter à l'instructrice ce
qu'il faut répondre au déclarant. Elles fonctionnent comme ça auj. car
Teleicare ne permet pas à la viseuse d'instruire le dossier et de répondre
directement au déclarant, mais ce serait bcp plus simple pour le BEPIAS si
la viseuse pouvait directement répondre au déclarant (plutôt que s'ajouter
un AR) --> demande d'Emmanuelle. Ma théorie c'est qu'une fois que la
viseuse pourra instruire le dossier, je pense que le nb de commentaires
destinés aux instructrices dans le cadre de l'analyse d'un dossier devrait
nettement diminuer... Donc je propose qu'on attende de voir ce qu'il en est
avant de travailler sur cette PR (pour voir si le besoin est tjrs
d'actualité ou non).

*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***


Le lun. 19 août 2024 à 09:31, Perrine L. ***@***.***> a
écrit :

**Comment by Fantine-py** [comment]
Oui c'est ça [@pletelli](https://github.com/pletelli) et [@alemangui](https://github.com/alemangui) pour info En fait, il y a 2 cas de figure:
 
- soit la viseuse est alignée avec la décision proposée par l'instructrice, auquel cas elle peut "confirmer" cette décision qui est alors envoyée au déclarant (déjà le cas auj.) 

- soit la viseuse n'est pas d'accord avec la décision proposée par l'instructrice, auquel cas elle va écrire un commentaire pour expliquer à l'instructrice pourquoi son avis diverge et dicter à l'instructrice ce qu'il faut répondre au déclarant. Elles fonctionnent comme ça auj. car Teleicare ne permet pas à la viseuse d'instruire le dossier et de répondre directement au déclarant, mais ce serait bcp plus simple pour le BEPIAS si la viseuse pouvait directement répondre au déclarant (plutôt que s'ajouter un AR) --> demande d'Emmanuelle. Ma théorie c'est qu'une fois que la viseuse pourra instruire le dossier, je pense que le nb de commentaires destinés aux instructrices dans le cadre de l'analyse d'un dossier devrait nettement diminuer... Donc je propose qu'on attende de voir ce qu'il en est avant de travailler sur cette PR (pour voir si le besoin est tjrs d'actualité ou non).

**Comment by pletelli** [comment]
Compris, merci :)
