### ISSUE TITLE
Distinguer pour l'étape du visa les rôles de viseur et de signataire

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#808]
Il faut prévoir 2 hyp : 

- hyp 1 : une même personne peut avoir à la fois les pouvoirs de viseur + signature -> auquel cas il faut qu'elle puisse faire ces 2 actions lors de la même étape. 

- hyp 2 : distinguer clairement 1 viseur et 1 signataire (auquel cas le viseur ne doit pas pouvoir signer). Dans ce cas de figure, il faut donner la possibilité au signataire de signer en 1 fois plusieurs déclarations. 

Cf. commentaire du BEPIAS : 
- _Prévoir la possibilité de viser et signer sans devoir rouvrir chaque dossier individuellement. Le fait d’avoir 2 étapes distinctes doit être conservé (cf. permet éventuellement de revenir en arrière si on a validé par erreur et ainsi éviter que le courrier ne soit envoyé) mais il faut trouver un système qui permette soit de viser et signer sous la même interface, soit de sélectionner tous les dossiers soumis à la signature et de les faire tous partir en un seul clic._

**Comment by Fantine-py** [comment]
@alemangui @pletelli après clarification avec Emmanuelle, ce double niveau de validation n'est pas réglementaire. C'est le BEPIAS qui a repris ça de Teleicare je pense... Donc j'aimerais bien essayer de les faire bouger sur ce point parce que si elles demandent que le signataire puissent signer 30 dossiers d'un coup sans prendre le temps de les ouvrir un par un, ça veut dire que le signataire ne checke rien, donc je pense qu'on peut challenger l'utilité de ce 2ème niveau de validation non ?

**Comment by alemangui** [comment]
Tout à fait d'accord, ça n'a pas trop de sens à mon avis de le garder

**Comment by pletelli** [comment]
Tout à fait d'accord aussi :)
On avait essayé de questionner ça aussi en séminaire, Emmanuelle n'était pas très décidée à changer d'avis. Mais clairement c'est un niveau de hierarchie qui semble assez absurde.

**Comment by HeleneDubourdieu** [comment]
traité ici https://github.com/betagouv/complements-alimentaires/issues/1267
