### ISSUE TITLE
Plateforme de déclaration : ouvrir la possibilité de rejoindre une entreprise (sans demander la co-gestion)

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#825]
Hello @alemangui , le chemin actuel permet seulement de demander à être co-gestionnaire d'une entreprise existante.
Il faudrait aussi prévoir la possibilité de devenir "déclarant" d'une entreprise existante.

Détail : (ne fais pas attention aux commentaires, je voulais au départ envoyer cette vidéo au BEPIAS pour leur présenter la nouvelle release) : 

https://www.loom.com/share/651e1e8ce3fe47f0b6f17b2e8b0da1fd?sid=cdfba46e-a1d0-403a-8b40-6500a4ca2933

Et ça me fait penser que sur l'écran du début on pourrait supprimer une carte car c'est 2 fois la même infos non ? 

![Image](https://github.com/user-attachments/assets/9f651eab-18cc-480f-892c-c721ff9959aa)

**Comment by alemangui** [comment]
@Fantine-py je me permet aussi d'ajouter les templates Brevo nécessaires pour ce procès

![image](https://github.com/user-attachments/assets/f382dc2d-a788-4c8f-bd42-60e9c12f81b7)
