### ISSUE TITLE
MAJ le contenu des mails que les pros reçoivent au fur et à mesure de l'instruction de leurs dossiers

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#828]
Voir ici : https://www.notion.so/betagouv-dinum/Relire-la-V2-des-mails-de-notif-30dffe76609b44f785beadf459ae2ae7

**Comment by Fantine-py** [comment]
Je n'ai pas eu le temps de relire les commentaires d'Emmanuelle, je le ferai en rentrant mais si vous voulez traiter l'issue avant no souci !

**Comment by alemangui** [comment]
Top merci ! Déjà côté dev on va envoyer les différentes variables nécessaires (nom du complément, jours d'expiration, etc) vers le template Brevo. On pourra aussi commencer à le rédiger, sachant que tu auras la main à tout moment pour le modifier directement dans Brevo

**Comment by alemangui** [comment]
Pour rappel, tous les templates sont dans Brevo : https://app.brevo.com/templates/listing
