### ISSUE TITLE
En tant qu'administrateur d'une entreprise, je dois connaître le nom de la personne qui demande à rejoindre l'entreprise

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#861]
Hello @alemangui 

aujourd'hui le nom de la personne qui demande à rejoindre une entreprise n'est pas indiqué dans le mail que reçoit l'administrateur de cette structure. Il faudrait l'ajouter dans l'objet + le corps du mail :)
 
**_Objet : [XXX] voudrait rejoindre [...]_**
_Madame, Monsieur [XXXX]_

(mais trop trop stylé que t'aies pu dev cette fonctionnalité la semaine dernière !!!!) 

![Image](https://github.com/user-attachments/assets/9e8d47ce-830a-4696-ba42-1530e6c2b937)

**Comment by alemangui** [comment]
Hello @Fantine-py 
Ceci arrive car sur ton compte tu n'as pas renseigné ton nom et prénom. Peux-tu retester une fois que tu les aura rempli dans l'admin?

**Comment by Fantine-py** [comment]
C'est allo good ! Désolée @alemangui
