### ISSUE TITLE
plateforme déclaration : créer la page de gestion des collaborateurs (pour les admins d'une entreprise)

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#862]
Hello,

Quand je clique sur le bouton "traiter la demande" dans le mail que je reçois en tant qu'admin pour m'informer que XXX veut rejoindre mon enterprise, je suis redirigée vers une page vide. 

Je peux réfléchir à une grossière maquette si besoin @alemangui ? 

![Image](https://github.com/user-attachments/assets/7b8de078-c32c-4eca-9ae7-825dff0cd07c)

**Comment by alemangui** [comment]
C'est un bug, la page existe déjà et devrait s'afficher, je regarde

**Comment by Fantine-py** [comment]
C'est allo good ! Désolée @alemangui

**Comment by Fantine-py** [comment]
C'est allo good ! Désolée @alemangui <https://github.com/alemangui>
*Fantine Monot*
Ministère de l'Agriculture et de la Souveraineté alimentaire | beta.gouv.
*fr*
06 32 32 89 82
***@***.***
