### ISSUE TITLE
En tant qu'utilisateur, je reçois un email chaque fois que mes rôles changent dans les entreprises auxquelles je suis affilié.

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#863]
Sauf erreur de ma part, pour le moment la personne ayant demandé à rejoindre X entreprise ne reçoit pas de mail l'informant que sa demande a été acceptée par l'administrateur ?

Il faudrait prévoir : 
- un mail de notif pour me dire que je suis désormais déclarant de X entreprise 
- un mail de notif pour me dire que je suis désormais gestionnaire de X entreprise
- un mail de notif pour me dire que je ne suis plus déclarant de X entreprise
- un mail de notif pour me dire que je ne suis plus gestionnaire de X entreprise

@alemangui je vais préparer des drafts de mails

**Comment by alemangui** [comment]
Suite au développement de la semaine dernière, les templates Brevo 12 à 18 sont envoyés suite à des évènements liés aux rôles dans une entreprise.

>  personne ayant demandé à rejoindre X entreprise ne reçoit pas de mail l'informant que sa demande a été acceptée par l'administrateur

Si, ce serait le template 13 (ou 14 si la demande a été refusée)

Il n'y a pas de différenciation suite au rôle, mais l'email contient le lien où on peut voir ce qu'on peut faire dans l'entreprise.

Lors qu'un rôle est enlevé on ne reçoit pas d'email, mais pas sur que ça soit _deadline de la muerte_ si ?

**Comment by Fantine-py** [comment]
Ok parfait. Ce n'est peut-être même pas utile de prévoir un mail pour prévenir la personne que son rôle a été supprimé ? Je propose de ne pas créer de ticket et de voir si ce sujet revient ?

**Comment by alemangui** [comment]
@Fantine-py tout à fait d'accord. Si ça te va je ferme l'issue mais n'hésite pas à le rouvrir si besoin
