### ISSUE TITLE
Mettre également une icone "lancer la recherche" dans la barre de recherche ingrédients dans l'onglet "composition" (quand je déclare un produit)

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#865]
Hello @alemangui,

possible d'ajouter cette loupe : 

![Image](https://github.com/user-attachments/assets/1718811b-b32e-43b3-8761-a2a01a7867a7)

### ici : 

![Image](https://github.com/user-attachments/assets/d9a1c509-6a2b-4231-9bea-97dd17b2b188)

**Comment by alemangui** [comment]
Je ne crois pas car le bouton ne ferait rien :thinking:  Contrairement aux autres endroits où ce champ se trouve, ici on n'a pas de "vue résultats", l'utilisateur doit forcément en choisir un depuis le dropdown.

**Comment by Fantine-py** [comment]
et c'est couteux d'implémenter ici une vue résultats @alemangui ? après on peut attendre de voir ce qui ressort des tests avec les pros. Perso je ne trouve pas ça hyper pratique mais c'est aussi lié au fait que je n'ai pas en tête un ingrédient ultra précis, tandis que ça doit être différent pour les pros quand ils déclarent la compo d'un produit.

**Comment by alemangui** [comment]
Ce serait un peu coûteux oui, vu qu'on est dans une vue onglet ça voudrait dire l'implémenter dans un modal. Ça me va d'attendre les tests :+1:

**Comment by alemangui** [comment]
@Fantine-py ça te va si on change la prio de cet issue ?
