### ISSUE TITLE
Plateforme démo : bugs dans le flow de déclaration d'un nouveau produit

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#873]
- [ ] les menus déroulants pour choisir la forme du complément alimentaire ne marchent pas (solide/liquide) + l'unité pour le poids 
 - [ ] le moteur de recherche "ingrédients" dans la section "composition" ne fonctionne pas

**Comment by alemangui** [comment]
Ces soucis sont dus au fait qu'on n'a pas encore fait l'import de données pour démo. Je verrai demain avec @pletelli pour le faire :)
