### ISSUE TITLE
bug staging : le filtre "déclarations non assignées" ne fonctionne pas

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#874]
https://www.loom.com/share/5128a9508cc948788b4d9964ea549560?sid=ffe84ef8-45d9-4222-bcfb-5e68b69e73c4

**Comment by alemangui** [comment]
Je n'arrive pas à le reproduire, je me demande si ça a été fixé par un autre commit ?

**Comment by Fantine-py** [comment]
Effectivement ça marche en staging maintenant ! Je ferme le ticket du coup @alemangui
