### ISSUE TITLE
Pouvoir nommer une stté en tant que mandataire

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#925]
Car dans certaines boîtes de conseil, c'est tous les salariés de la boîte qui peuvent déclarer pour toutes les entreprises + changement régulier avec les stagiaires, alternants etc. --> assez contraignant pour les gestionnaires d'entreprises de devoir sans cesse maj la liste des mandataires. 

Et si on reporte le charge sur le mandant ayant le statut de gestionnaire c'est pire, car ça signifierait que s'ils ont 50 entreprises pour lesquelles ils ont un mandat, il devrait faire la manip 50 fois pour MAJ la nouvelle adresse mail du nouveau stagiaire (si je grossis le trait). 

En tout état de cause, il faudrait bien préciser le process pour le lancement.

**Comment by Fantine-py** [comment]
https://github.com/user-attachments/assets/981541b0-1c00-4ee3-b3ab-cc7f47a1c662

**Comment by Fantine-py** [comment]
donner un droit à l'entreprise qui a tel SIRET

**Comment by hfroot** [comment]
## Questions

Si on parle de Soc A (la société qui nomme une stté mandataire... la société mandatée ?) et Soc M (la société mandataire) :

Est-ce que Soc M peut faire des déclarations pour Soc M ainsi que Soc A ?

Est-ce que les déclarants de Soc A peuvent voir les déclarations faites par Soc M ?

Est-ce que Soc M peut aussi nommer une société mandataire ?

Quand une gestionnaire de Soc A nomme Soc M comme mandataire, est-ce que la gestionnaire peut voir les noms des gestionnaires et déclarant.e.s de Soc M ?

Si Soc M est enlévé comme mandataire, est-ce que les déclarations faites par Soc M pour Soc A restent avec Soc A, et les membres de Soc M perdent la vue de ces déclarations ?

Est-ce que les instructrices ont besoin de voir quelque part dans le dossier que l'auteur fait partie d'une société mandataire et non pas le société de la déclaration ? Quelles données ?

Quelles notifications à envoyer quand ?

Est-ce que Soc M peut être la société mandataire pour plusieurs sociétés, disons Soc A et Soc B ?

**Comment by HeleneDubourdieu** [comment]
Hello

@hfroot 

Voici mes idées de réponses.

Si on parle de Soc A (la société qui nomme une stté mandataire... la société mandatée ?) et Soc M (la société mandataire) :

Est-ce que Soc M peut faire des déclarations pour Soc M ainsi que Soc A ? **OUI**

Est-ce que les déclarants de Soc A peuvent voir les déclarations faites par Soc M ? **OUI** si déclaration faite pour la Soc A. Si décla faite pour la Soc M non

Est-ce que Soc M peut aussi nommer une société mandataire ? **De sa société oui mais la Soc M ne peut pas nommer une société mandataire de la Soc A**

Quand une gestionnaire de Soc A nomme Soc M comme mandataire, est-ce que la gestionnaire peut voir les noms des gestionnaires et déclarant.e.s de Soc M ? **J'identifie pas de risque à mon sens**

Si Soc M est enlevée comme mandataire, est-ce que les déclarations faites par Soc M pour Soc A restent avec Soc A, et les membres de Soc M perdent la vue de ces déclarations ? **A mon sens oui (vérifier avec Emmanuelle)**

Est-ce que les instructrices ont besoin de voir quelque part dans le dossier que l'auteur fait partie d'une société mandataire et non pas le société de la déclaration ? Quelles données ? **(vérifier avec Emmanuelle)**

Quelles notifications à envoyer quand ? **à qui ?**

Est-ce que Soc M peut être la société mandataire pour plusieurs sociétés, disons Soc A et Soc B ? **oui** 

Est-ce que Soc M peut nommer Soc A comme la société qu'iels mandatent (j'invente des mots maintenant 😅) ? **oui**
