### ISSUE TITLE
Quand je crée un nouvel ingrédient, la carte ne s'affiche pas si je n'ajoute pas un autre ingrédient à la suite + on ne me demande pas la DJR

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#927]
https://www.loom.com/share/b6123d6c85644f5c875af4026275871d?sid=79ca8351-26e2-406a-9b9e-658a927bb20f 

ça bug pour :
- forme d'apport
- arome
- additif
- ingrédient actif
- ingrédient non actif

Il y a 2 choses : 

**1.** D'une part la carte ne s'affiche que si on ajoute un autre ingrédient derrière (comme si c'était l'action d'ajouter un autre ingrédient qui la faisait apparaître) ;

**2.** D'autre part, on ne demande pas de remplir la DJR.

**Comment by alemangui** [comment]
Merci Fantine. Concernant le premier point, j'ai créé l'issue #933 pour le suivre. La PR #934 devrait le résoudre.

Concernant le tableau de substances, @pletelli c'est lié au fait que les ingrédients ajoutés n'ont pas de substance liée non ? Est-ce que le fait de permettre l'ajout des nouvelles substances pourrait adresser le besoin en MVP ?
