### ISSUE TITLE
Bug affichage ajout nouvel ingrédient n'apparaissant pas dans la bdd lors d'une décla

### ISSUE THREAD

**Issue by amandinegueg** [betagouv/complements-alimentaires#937]
Lors de la création d'un nouvel ingrédient "Forme Apport" et "Ingrédient actifs", le nouvel ingrédient n'apparait pas dans la page Composition. La manip doit être renouvelée plusieurs fois pour qu'il s'affiche. Il peut apparaitre en doublon ensuite.

**Comment by alemangui** [comment]
Normalement fixé avec https://github.com/betagouv/complements-alimentaires/pull/934
