### ISSUE TITLE
Retour tests jenn - fin déc

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/complements-alimentaires#94]
coucou, je viens de tester 

1. la création d'un webinaire. quelques remarques mineures : 
- ajouter un comportement au hoover, une drop-shadow ? 
- ajouter l'année dans la date affichée pour le webinaire
- l'heure s'affiche sans le 2ème chiffre pr les minutes
- ajouter l'heure de fin
- target="_blank" pour le lien d'inscription pour ouvrir un nouvel onglet pr l'inscription afin de ne pas quitter la plateforme + le signifier dans le bouton

![Image](https://github.com/betagouv/complements-alimentaires/assets/36134318/278d441b-a02e-4f9d-882a-8d13e4d19531)

2. les articles de blog

- ds l'affichage du blog version abrégée, les caractères spéciaux sont codés

![Image](https://github.com/betagouv/complements-alimentaires/assets/36134318/6e684fa4-5ac0-42c7-9faa-37a72f9d42cd)

**Comment by alemangui** [comment]
Hello @JenniferStephan, 

> ajouter un comportement au hoover, une drop-shadow ?

J'éviterais car la carte elle même n'est pas cliquable car elle a un bouton à l'intérieur. De plus comme ça le texte reste sélectionnable. Si on ajoute un _hover_ alors que le click ne fait rien ça peut confondre un peu.

> ajouter l'année dans la date affichée pour le webinaire

Vu qu'on ajoute seulement les webinaires à venir, est-ce qu'on risque d'en avoir planifié à plus d'un an dans le futur ?

Les autres éléments seront traités ici : https://github.com/betagouv/complements-alimentaires/pull/122
