### ISSUE TITLE
Interface de déclaration : auj. il est possible d’ajouter plusieurs fois un même ingrédient --> il faudrait bloquer cela

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#942]
![Image](https://github.com/user-attachments/assets/c669b8fc-aca6-4850-b95c-fe980840002e)

**Comment by Fantine-py** [comment]
@alemangui @pletelli je rouve ce ticket car en testant je me rends compte qu'on a zappé un cas de figure : si le pro veut déclarer dans sa compo 2 parties différentes d'une même plante 😬 Ce n'est maintenant plus possible.

**Comment by alemangui** [comment]
Je commence par faire un revert ici : https://github.com/betagouv/complements-alimentaires/pull/1038

En attendant une PR plus complète pour détecter les doublons

**Comment by alemangui** [comment]
Lié à #1051

**Comment by HeleneDubourdieu** [comment]
[![Image](https://github.com/user-attachments/assets/0728e64d-f544-441e-adbf-cb8a47094ecb)
]

Problème résolu, je ferme le ticket
