### ISSUE TITLE
bug site demo : en tant que déclarant je n'ai plus accès à l'édition de mon brouillon

### ISSUE THREAD

**Issue by Fantine-py** [betagouv/complements-alimentaires#943]
https://www.loom.com/share/af34c69d6f3745248af9197e1880a959?focus_title=1&muted=1&from_recorder=1

**Comment by alemangui** [comment]
Normalement ça devrait être fixé après la mise en prod de Perrine avec :

PRs liées :
- #944 
- #938 
- #946
- #948
